// coverage-write.test.js — src/write.js gaps: genContext manifest generation,
// the backup millisecond-collision loop, pruneBackups failure branches, the
// full ensureMcp matrix (6 config files × add/present/skip/dry/parse-error) and
// the removeMcpAdditions rollback matrix (toml/jsonc/json × removed/kept).
// Isolated: AIO_STATE_DIR → temp (before the src import), every agent home is a
// temp dir behind t.mock.method(os, 'homedir') — never the real user home.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

process.env.AIO_STATE_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-write-cov-')); // must precede the src import

const { genContext, backup, pruneBackups, ensureMcp, removeMcpAdditions, ledgerFile } = await import('../src/write.js');
const { STATE_DIR, BACKUP_DIR } = await import('../src/paths.js');

const KEY = 'codebase-memory-mcp';
const BIN = 'npx -y codebase-memory-mcp';
const LEDGER = path.join(STATE_DIR, 'mcp-ledger.json');

/** Fresh temp home so ensureMcp never reads the real ~/.claude.json & friends. */
function fixtureHome(t) {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-write-home-'));
  t.mock.method(os, 'homedir', () => home);
  t.after(() => fs.rmSync(home, { recursive: true, force: true }));
  return home;
}

function write(p, content) {
  fs.mkdirSync(path.dirname(p), { recursive: true });
  fs.writeFileSync(p, content);
  return p;
}

function read(p) {
  return fs.readFileSync(p, 'utf8');
}

function putLedger(entries) {
  fs.mkdirSync(STATE_DIR, { recursive: true });
  fs.writeFileSync(LEDGER, JSON.stringify(entries, null, 2));
}

function readLedger() {
  return JSON.parse(read(LEDGER));
}

/* ---------------- genContext (lines 166–186) ---------------- */

test('genContext: slim manifest — version stamp, live-architecture note, agents table, no duplicated rules', () => {
  const out = path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'aio-genctx-')), 'nested', 'aio-context.md');

  genContext(
    {
      version: '9.9.9',
      agents: [
        { name: 'claude', found: true, bin: 'claude' },
        { name: 'kimi', found: false, bin: null },
      ],
    },
    out
  );

  assert.ok(fs.existsSync(out), 'outPath (incl. missing parent dirs) written');
  const txt = read(out);
  assert.match(txt, /^<!-- AUTO-GENERATED by aio v9\.9\.9 on \d{4}-\d{2}-\d{2}T/, 'generator stamp on line 1');
  assert.ok(txt.includes('# AIO Context Manifest'), 'manifest title');
  assert.ok(txt.includes('Live architecture — zero search storage'), 'zero-storage note');
  assert.ok(txt.includes('## AGENTS DETECTED'), 'agents section');
  assert.ok(txt.includes('- claude: found (`claude`)'), 'found agent with its binary');
  assert.ok(txt.includes('- kimi: not installed'), 'missing agent reported');
  assert.ok(!txt.includes('Auto-use rules'), 'rules live only in the injected block (M-04)');
  assert.equal(
    txt.split('AIO AUTO-CONTEXT').length - 1,
    1,
    'header appears only as a prose mention ("rules live in the AIO AUTO-CONTEXT block"), never as a duplicated block'
  );
  assert.ok(!txt.includes('USAGE DISCLOSURE'), 'no injected block rules leaked into the manifest');
});

/* ---------------- backup collision (lines 19–22) ---------------- */

test('backup: millisecond-name collision → the loop picks the _1 name instead of overwriting', (t) => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-backup-coll-'));
  const src = path.join(dir, 'src.txt');
  fs.writeFileSync(src, 'payload');
  const origExists = fs.existsSync.bind(fs);
  let collisionReported = false;
  t.mock.method(fs, 'existsSync', (p) => {
    const s = String(p);
    // first probe of the plain millisecond-stamped dest → pretend it already
    // exists (the CI race); the _1 fallback must then be taken for real
    if (!collisionReported && /__src\.txt$/.test(s) && !/_\d+__src\.txt$/.test(s)) {
      collisionReported = true;
      return true;
    }
    return origExists(p);
  });

  const dest = backup(src, 'coll');

  assert.equal(collisionReported, true, 'collision branch exercised');
  assert.match(path.basename(dest), /^coll__.*_1__src\.txt$/, `_1 suffix chosen: ${path.basename(dest)}`);
  assert.equal(read(dest), 'payload', 'backup copy carries the original bytes');
});

/* ---------------- pruneBackups failure branches (lines 226–232) ---------------- */

test("pruneBackups: a backup that cannot be stat'ed is skipped; fresh ones stay", (t) => {
  fs.rmSync(BACKUP_DIR, { recursive: true, force: true });
  fs.mkdirSync(BACKUP_DIR, { recursive: true });
  const locked = path.join(BACKUP_DIR, 'inject__locked__a.md');
  const fresh = path.join(BACKUP_DIR, 'inject__fresh__b.md');
  fs.writeFileSync(locked, 'locked');
  fs.writeFileSync(fresh, 'fresh');
  const origStat = fs.statSync.bind(fs);
  t.mock.method(fs, 'statSync', (p) => {
    if (String(p) === locked) throw new Error('EBUSY: resource busy or locked');
    return origStat(p);
  });

  assert.equal(pruneBackups(30), 0, 'locked entry skipped, fresh one not old enough');
  assert.ok(fs.existsSync(locked), 'locked backup kept for the next run');
  assert.ok(fs.existsSync(fresh), 'fresh backup kept');
});

test('pruneBackups: no backups dir yet → 0 removed, no throw (read-only home path)', () => {
  fs.rmSync(BACKUP_DIR, { recursive: true, force: true });
  assert.equal(pruneBackups(30), 0, 'absent dir is not an error');
  assert.equal(fs.existsSync(BACKUP_DIR), false, 'prune never creates the dir');
});

/* ---------------- ensureMcp matrix (lines 322–340 + 291–318) ---------------- */

test('ensureMcp: add matrix — opencode jsonc (empty mcp block), claude/kimi/gemini JSON, codex toml, jcode skipped', (t) => {
  const home = fixtureHome(t);
  const jsonc = write(path.join(home, '.config', 'opencode', 'opencode.jsonc'), '{\n  "mcp": {}\n}\n');
  write(path.join(home, '.claude.json'), JSON.stringify({ mcpServers: {} }, null, 2) + '\n');
  write(path.join(home, '.kimi-code', 'mcp.json'), JSON.stringify({ mcpServers: {} }, null, 2) + '\n');
  fs.mkdirSync(path.join(home, '.jcode'), { recursive: true }); // dir present, file absent → skipped
  fs.mkdirSync(path.join(home, '.gemini'), { recursive: true }); // dir present → bootstrap (create=true)
  write(path.join(home, '.codex', 'config.toml'), 'model = "g"\n');

  const res = ensureMcp(BIN);

  assert.deepEqual(
    res.map((r) => r.target),
    ['opencode.jsonc', '.claude.json', 'mcp.json', 'mcp.json', 'settings.json', 'config.toml'],
    'all six config slots reported in order'
  );
  assert.deepEqual(
    res.map((r) => r.status),
    ['added', 'added', 'added', 'file not found — skipped', 'added', 'added'],
    `matrix statuses: ${JSON.stringify(res)}`
  );

  const j = read(jsonc);
  assert.equal(
    j.split(`"${KEY}":`).length - 1,
    1,
    'exactly one key inserted (the command string also mentions the key, so count key: sites)'
  );
  assert.ok(j.includes('added by aio'), 'rollback marker comment present inside the entry');
  assert.ok(!/,\s*\n\}\s*$/.test(j.replace(/"codebase-memory-mcp"[\s\S]*?\}\s*/, '')), 'no trailing comma after an empty-block insert');

  const claude = JSON.parse(read(path.join(home, '.claude.json')));
  assert.deepEqual(claude.mcpServers[KEY], { command: BIN }, 'claude entry written under mcpServers');
  const gemini = JSON.parse(read(path.join(home, '.gemini', 'settings.json')));
  assert.deepEqual(gemini.mcpServers[KEY], { command: BIN }, 'gemini bootstrapped from nothing (create=true)');
  const kimi = JSON.parse(read(path.join(home, '.kimi-code', 'mcp.json')));
  assert.deepEqual(kimi.mcpServers[KEY], { command: BIN }, 'kimi entry written');
  const codex = read(path.join(home, '.codex', 'config.toml'));
  assert.ok(codex.includes(`[mcp_servers.${KEY}]`), 'toml table appended');
  assert.ok(codex.includes('model = "g"'), 'pre-existing toml content kept');
  assert.ok(!fs.existsSync(path.join(home, '.jcode', 'mcp.json')), 'skipped slot stays absent');
});

test('ensureMcp: rerun on the wired home → every slot "present" (idempotent, files byte-stable)', (t) => {
  const home = fixtureHome(t);
  write(path.join(home, '.config', 'opencode', 'opencode.jsonc'), '{\n  "mcp": {}\n}\n');
  write(path.join(home, '.claude.json'), JSON.stringify({ mcpServers: {} }, null, 2) + '\n');
  write(path.join(home, '.kimi-code', 'mcp.json'), JSON.stringify({ mcpServers: {} }, null, 2) + '\n');
  write(path.join(home, '.gemini', 'settings.json'), JSON.stringify({ mcpServers: {} }, null, 2) + '\n');
  write(path.join(home, '.codex', 'config.toml'), 'model = "g"\n');
  ensureMcp(BIN);
  const before = [
    path.join(home, '.config', 'opencode', 'opencode.jsonc'),
    path.join(home, '.claude.json'),
    path.join(home, '.kimi-code', 'mcp.json'),
    path.join(home, '.gemini', 'settings.json'),
    path.join(home, '.codex', 'config.toml'),
  ].map(read);

  const res = ensureMcp(BIN);

  assert.deepEqual(
    res.map((r) => r.status),
    ['present', 'present', 'present', 'file not found — skipped', 'present', 'present'],
    `rerun reports present: ${JSON.stringify(res)}`
  );
  assert.deepEqual(before, [
    path.join(home, '.config', 'opencode', 'opencode.jsonc'),
    path.join(home, '.claude.json'),
    path.join(home, '.kimi-code', 'mcp.json'),
    path.join(home, '.gemini', 'settings.json'),
    path.join(home, '.codex', 'config.toml'),
  ].map(read), 'idempotent rerun rewrote nothing');
  assert.ok(readLedger().some((e) => e.file.endsWith('opencode.jsonc') && e.key === KEY), 'self-healing ledger re-recorded');
});

test('ensureMcp: opencode jsonc without an "mcp" block → skipped; parse error in claude surfaced, not thrown', (t) => {
  const home = fixtureHome(t);
  const jsonc = write(path.join(home, '.config', 'opencode', 'opencode.jsonc'), '{\n  "model": "x"\n}\n');
  const bad = write(path.join(home, '.claude.json'), '{not json at all');

  const res = ensureMcp(BIN);

  assert.equal(res[0].target, 'opencode.jsonc');
  assert.equal(res[0].status, 'no "mcp" block — skipped', 'jsonc without the marker is left alone');
  assert.equal(read(jsonc), '{\n  "model": "x"\n}\n', 'jsonc untouched');
  assert.match(res[1].status, /^parse error: /, `claude parse error reported: ${res[1].status}`);
  assert.equal(read(bad), '{not json at all', 'malformed file never overwritten');
  assert.equal(res[4].status, 'file not found — skipped', 'gemini without its dir is skipped');
});

test('ensureMcp: jsonc with a NON-empty "mcp" block → comma after the new entry; dry → plan only', (t) => {
  const home = fixtureHome(t);
  const original = '{\n  "mcp": {\n    "other-tool": { "command": "x" }\n  }\n}\n';
  const jsonc = write(path.join(home, '.config', 'opencode', 'opencode.jsonc'), original);

  const dry = ensureMcp(BIN, { dry: true });
  assert.equal(dry[0].status, 'would add (dry-run)', 'dry plan for the jsonc slot');
  assert.equal(read(jsonc), original, 'dry run writes nothing');
  assert.equal(dry[4].status, 'file not found — skipped', 'missing slots stay skipped even in dry mode');

  const real = ensureMcp(BIN);
  assert.equal(real[0].status, 'added', 'non-empty block accepts the insert');
  const j = read(jsonc);
  assert.ok(j.includes(KEY), 'entry present');
  assert.ok(/,\n\s*"other-tool"/.test(j), `comma separates entry from the next key:\n${j}`);
  assert.ok(j.includes('"other-tool": { "command": "x" }'), 'pre-existing entry kept');
});

/* ---------------- removeMcpAdditions matrix (lines 353–409) ---------------- */

test('removeMcpAdditions: missing + already-gone + toml removed + toml partial-removal keep', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-rm-mcp-a-'));
  const missing = path.join(dir, 'missing.json'); // never created
  const gone = write(path.join(dir, 'gone.json'), JSON.stringify({ mcpServers: { other: 1 } }, null, 2));
  const okToml = write(
    path.join(dir, 'ok.toml'),
    `model = "g"\n\n[mcp_servers.${KEY}]\n# added by aio — remove via \`aio rollback\`\ncommand = "x"\n`
  );
  const badToml = write(
    path.join(dir, 'bad.toml'),
    `[mcp_servers.${KEY}]\ncommand = "x"\n[.note]\n${KEY} must stay visible\n`
  );
  putLedger([
    { file: missing, key: KEY },
    { file: gone, key: KEY },
    { file: okToml, key: KEY },
    { file: badToml, key: KEY },
  ]);

  const out = removeMcpAdditions();

  assert.deepEqual(
    out.map((o) => o.status),
    [
      'missing — ledger entry kept for retry',
      'already gone',
      'removed',
      'unsupported layout — manual removal needed, ledger entry kept',
    ],
    `per-file statuses: ${JSON.stringify(out)}`
  );
  assert.ok(!fs.existsSync(missing), 'missing file stays missing');
  assert.equal(read(gone), JSON.stringify({ mcpServers: { other: 1 } }, null, 2), 'already-gone file untouched');
  const cleaned = read(okToml);
  assert.ok(cleaned.includes('model = "g"'), 'unrelated toml content survives');
  assert.ok(!cleaned.includes(KEY), `aio table fully removed:\n${cleaned}`);
  assert.equal(read(badToml), `[mcp_servers.${KEY}]\ncommand = "x"\n[.note]\n${KEY} must stay visible\n`, 'partial-removal layout untouched');
  assert.deepEqual(
    readLedger().map((e) => path.basename(e.file)),
    ['missing.json', 'bad.toml'],
    'kept entries = missing + unsupported, dropped = removed + already gone'
  );
});

test('removeMcpAdditions: jsonc flat entry removed; nested-object entry kept as unsupported', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-rm-mcp-b-'));
  const okJsonc = write(
    path.join(dir, 'ok.jsonc'),
    `{\n  "mcp": {\n    "${KEY}": { "type": "local", "command": "x" },\n    "other": { "command": "y" }\n  }\n}\n`
  );
  const nestedJsonc = write(
    path.join(dir, 'nested.jsonc'),
    `{\n  "mcp": {\n    "${KEY}": { "nested": { "a": 1 } },\n    "other": { "command": "y" }\n  }\n}\n`
  );
  putLedger([
    { file: okJsonc, key: KEY },
    { file: nestedJsonc, key: KEY },
  ]);

  const out = removeMcpAdditions();

  assert.equal(out[0].status, 'removed');
  assert.equal(out[1].status, 'unsupported layout — manual removal needed, ledger entry kept');
  const cleaned = read(okJsonc);
  assert.ok(!cleaned.includes(KEY), `flat entry gone:\n${cleaned}`);
  assert.ok(cleaned.includes('"other": { "command": "y" }'), 'sibling entry survives');
  assert.ok(cleaned.includes('"mcp"'), 'the mcp block itself survives');
  assert.equal(read(nestedJsonc).split(KEY).length - 1, 1, 'nested layout byte-identical');
  assert.deepEqual(readLedger().map((e) => path.basename(e.file)), ['nested.jsonc'], 'only the unremovable one kept');
});

test('removeMcpAdditions: json key removal — mcpServers root, top-level root, substring-only, parse error', () => {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-rm-mcp-c-'));
  const underRoot = write(
    path.join(dir, 'under-root.json'),
    JSON.stringify({ mcpServers: { [KEY]: { command: 'x' }, other: { command: 'y' } } }, null, 2) + '\n'
  );
  const atRoot = write(path.join(dir, 'at-root.json'), JSON.stringify({ [KEY]: { command: 'x' } }, null, 2) + '\n');
  const substring = write(path.join(dir, 'substring.json'), JSON.stringify({ [KEY + '-v2']: 1 }, null, 2) + '\n');
  const broken = write(path.join(dir, 'broken.json'), `{"${KEY}": broken`);
  putLedger([
    { file: underRoot, key: KEY },
    { file: atRoot, key: KEY },
    { file: substring, key: KEY },
    { file: broken, key: KEY },
  ]);

  const out = removeMcpAdditions();

  assert.deepEqual(
    out.slice(0, 3).map((o) => o.status),
    [
      'removed',
      'removed',
      'unsupported layout — manual removal needed, ledger entry kept',
    ],
    `json matrix: ${JSON.stringify(out)}`
  );
  assert.match(out[3].status, /^parse error — skipped, ledger entry kept \(/, 'parse error carried in the status');
  const a = JSON.parse(read(underRoot));
  assert.equal(KEY in a.mcpServers, false, 'entry deleted from mcpServers');
  assert.ok(a.mcpServers.other, 'sibling entry kept');
  const b = JSON.parse(read(atRoot));
  assert.equal(KEY in b, false, 'top-level entry deleted');
  assert.equal(read(substring), JSON.stringify({ [KEY + '-v2']: 1 }, null, 2) + '\n', 'substring-only file untouched');
  assert.equal(read(broken), `{"${KEY}": broken`, 'malformed file untouched');
  assert.deepEqual(
    readLedger().map((e) => path.basename(e.file)),
    ['substring.json', 'broken.json'],
    'unremovable entries stay in the ledger for a retry'
  );
});
