// coverage-doctor.test.js — src/doctor.js gaps: node check warn/bad/bun lines,
// live+ollama+gh probe failure lanes, manifest stale/legacy, agent-block missing,
// all four mcp-ledger branches, and the `--fix` spawn paths (success text+json,
// spawn failure). Isolated: AIO_STATE_DIR → temp; every home is a temp dir behind
// t.mock.method(os, 'homedir'); PATH emptied so the real gh is never found.
// NO AIO_NO_GH here — the gh probe must actually spawn (ENOENT → warn lane).
process.env.AIO_STATE_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-doctor-cov-'));

import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { test } from 'node:test';
import assert from 'node:assert/strict';

const { runChecks, runDoctor, aioBinPath } = await import('../src/doctor.js');
const { STATE_DIR } = await import('../src/paths.js');
const { BLOCK_START, BLOCK_END } = await import('../src/write.js');

const MANIFEST = path.join(STATE_DIR, 'aio-context.md');
const LEDGER = path.join(STATE_DIR, 'mcp-ledger.json');
const CONFIG = path.join(STATE_DIR, 'config.json');

const FRESH_MANIFEST = [
  '<!-- AUTO-GENERATED by aio v9.0.0 - do not edit -->',
  '',
  '# AIO Context Manifest',
  '',
  '> **Live architecture - zero search storage.** live.',
  '',
  '## AGENTS DETECTED',
  '',
].join('\n');

function json(body) {
  return new Response(JSON.stringify(body), { status: 200, headers: { 'content-type': 'application/json' } });
}

/** Probe control: github / ollama answer or fail independently; never real network. */
function mockNet(t, { github = 'ok', ollama = 'ok' } = {}) {
  return t.mock.method(globalThis, 'fetch', async (input) => {
    const url = String(input instanceof Request ? input.url : input);
    if (url.includes('api.github.com')) {
      if (github === 'ok') return json({ resources: {} });
      throw new Error('connect ECONNREFUSED 140.82.112.9:443');
    }
    if (url.includes('/api/tags')) {
      if (ollama === 'ok') return json({ models: [{ name: 'qwen3:4b' }] });
      throw new Error('connect ECONNREFUSED 127.0.0.1:11434');
    }
    throw new Error(`unexpected network call in test: ${url}`);
  });
}

/** Temp home + inert PATH/APPDATA: detectAgents/blockTargets never see the real machine. */
function hermeticHome(t, { withBlock = false, withClaudeDir = false } = {}) {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-doctor-cov-home-'));
  if (withBlock) fs.writeFileSync(path.join(home, 'AGENTS.md'), `${BLOCK_START}\nmocked\n${BLOCK_END}\n`);
  if (withClaudeDir) fs.mkdirSync(path.join(home, '.claude'), { recursive: true }); // dir without CLAUDE.md
  const saved = { PATH: process.env.PATH, APPDATA: process.env.APPDATA };
  process.env.PATH = '';
  process.env.APPDATA = path.join(home, 'AppData', 'Roaming'); // absent → zed target dropped
  t.mock.method(os, 'homedir', () => home);
  t.after(() => {
    if (saved.PATH === undefined) delete process.env.PATH;
    else process.env.PATH = saved.PATH;
    if (saved.APPDATA === undefined) delete process.env.APPDATA;
    else process.env.APPDATA = saved.APPDATA;
    fs.rmSync(home, { recursive: true, force: true });
  });
  return home;
}

function check(r, id) {
  const c = r.checks.find((x) => x.id === id);
  assert.ok(c, `check "${id}" present in ${r.checks.map((x) => x.id).join(', ')}`);
  return c;
}

/* ---------------- node version lanes (lines 66–74) ---------------- */

test('runChecks: unsupported node majors → warn (18+) and bad (<18), supported restores', async (t) => {
  mockNet(t);
  hermeticHome(t);
  fs.rmSync(MANIFEST, { force: true });
  const desc = Object.getOwnPropertyDescriptor(process.versions, 'node');
  t.after(() => Object.defineProperty(process.versions, 'node', desc));

  Object.defineProperty(process.versions, 'node', { value: '20.10.0', configurable: true, enumerable: true });
  const warnR = await runChecks({});
  const warn = check(warnR, 'node');
  assert.equal(warn.level, 'warn', 'node 20 runs but is unsupported');
  assert.match(warn.detail, /runs, but unsupported; install Node >= 22/);

  Object.defineProperty(process.versions, 'node', { value: '16.0.0', configurable: true, enumerable: true });
  const badR = await runChecks({});
  const bad = check(badR, 'node');
  assert.equal(bad.level, 'bad', 'node < 18 is a hard fail');
  assert.match(bad.detail, /Node >= 22 required/);
  assert.equal(badR.ok, false, 'a bad node line fails the run');
});

test('runChecks: bun build → supported line names the bun version', async (t) => {
  mockNet(t);
  hermeticHome(t);
  fs.rmSync(MANIFEST, { force: true });
  Object.defineProperty(process.versions, 'bun', { value: '1.1.0', configurable: true, enumerable: true });
  t.after(() => {
    delete process.versions.bun;
  });

  const r = await runChecks({});
  const node = check(r, 'node');
  assert.equal(node.level, 'ok');
  assert.match(node.detail, /bun 1\.1\.0 build/, 'bun runtime called out');
});

/* ---------------- probe lanes (lines 28–54, 85–91, 134–147) ---------------- */

test('runChecks: github down + ollama down + real gh spawn (PATH inert) → three warns, 2 fetches', async (t) => {
  const net = mockNet(t, { github: 'fail', ollama: 'fail' });
  hermeticHome(t); // AIO_NO_GH unset → probeGhAuth really spawns `gh auth status`
  fs.rmSync(MANIFEST, { force: true });

  const r = await runChecks({});

  const live = check(r, 'live');
  assert.equal(live.level, 'warn');
  assert.match(live.detail, /github unreachable \(connect ECONNREFUSED/, 'failure reason surfaced');
  assert.match(live.detail, /aio ask will still try npm\/crates/);
  const ollama = check(r, 'ollama');
  assert.equal(ollama.level, 'warn');
  assert.match(ollama.detail, /not reachable — ask rerank skipped/);
  const gh = check(r, 'gh auth');
  assert.equal(gh.level, 'warn', 'gh present but unauthenticated/missing → warn');
  assert.match(gh.detail, /not logged in/);
  assert.equal(net.mock.callCount(), 2, 'github + ollama probed once each');
  assert.equal(r.ok, false, 'warns alone never fail; a missing manifest does');
});

/* ---------------- manifest freshness lanes (lines 94–109) ---------------- */

test('runChecks: live-layout manifest older than 7 days → stale warn', async (t) => {
  mockNet(t);
  hermeticHome(t, { withBlock: true });
  fs.writeFileSync(MANIFEST, FRESH_MANIFEST);
  const old = new Date(Date.now() - 10 * 86400000);
  fs.utimesSync(MANIFEST, old, old);

  const r = await runChecks({});
  const m = check(r, 'manifest');
  assert.equal(m.level, 'warn');
  assert.match(m.detail, /live architecture \(no search storage\)/);
  assert.match(m.detail, /stale \(>7d\) — refresh: aio/);
});

test('runChecks: legacy manifest (no live architecture) → bad LEGACY layout', async (t) => {
  mockNet(t);
  hermeticHome(t, { withBlock: true });
  fs.writeFileSync(MANIFEST, '<!-- old -->\n# Legacy manifest\nno live note here\n');

  const r = await runChecks({});
  const m = check(r, 'manifest');
  assert.equal(m.level, 'bad');
  assert.match(m.detail, /LEGACY layout/);
  assert.match(m.detail, /fix: aio --fix/);
  assert.equal(r.ok, false);
});

/* ---------------- agent-blocks lane (lines 113–127) ---------------- */

test('runChecks: an installed agent dir without the block → bad, label named', async (t) => {
  mockNet(t);
  hermeticHome(t, { withClaudeDir: true }); // ~/.claude exists, CLAUDE.md has no block
  fs.writeFileSync(MANIFEST, FRESH_MANIFEST);

  const r = await runChecks({});
  const blocks = check(r, 'agent blocks');
  assert.equal(blocks.level, 'bad');
  assert.match(blocks.detail, /0\/1 injected — missing: claude/, `labels the gap: ${blocks.detail}`);
  assert.equal(r.ok, false, 'missing block is an issue');
});

/* ---------------- mcp ledger lanes (lines 149–181) ---------------- */

test('runChecks: ledger absent + state present → warn to re-record for rollback', async (t) => {
  mockNet(t);
  hermeticHome(t, { withBlock: true });
  fs.writeFileSync(MANIFEST, FRESH_MANIFEST);
  fs.writeFileSync(CONFIG, JSON.stringify({ version: '9.0.0' }));
  fs.rmSync(LEDGER, { force: true });

  const r = await runChecks({});
  const ledger = check(r, 'mcp ledger');
  assert.equal(ledger.level, 'warn');
  assert.match(ledger.detail, /ledger missing — re-run `aio` to re-record MCP entries for rollback/);
});

test('runChecks: ledger broken entries (missing/gone/jsonc/toml/parse) → joined warn; valid → ok', async (t) => {
  mockNet(t);
  hermeticHome(t, { withBlock: true });
  fs.writeFileSync(MANIFEST, FRESH_MANIFEST);
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-ledger-fix-'));
  t.after(() => fs.rmSync(dir, { recursive: true, force: true }));
  const KEY = 'codebase-memory-mcp';
  const goneJsonc = path.join(dir, 'opencode.jsonc');
  const goneToml = path.join(dir, 'config.toml');
  const parseBad = path.join(dir, 'broken.json');
  const entryGone = path.join(dir, 'entry.json');
  const valid = path.join(dir, 'ok.json');
  fs.writeFileSync(goneJsonc, '{ "mcp": {} }');
  fs.writeFileSync(goneToml, 'model = "g"\n');
  fs.writeFileSync(parseBad, '{ not json');
  fs.writeFileSync(entryGone, JSON.stringify({ other: 1 }));
  fs.writeFileSync(valid, JSON.stringify({ mcpServers: { [KEY]: { command: 'x' } } }));
  const missing = path.join(dir, 'missing.json'); // never created

  fs.writeFileSync(
    LEDGER,
    JSON.stringify(
      [
        { file: missing, key: KEY },
        { file: goneJsonc, key: KEY },
        { file: goneToml, key: KEY },
        { file: parseBad, key: KEY },
        { file: entryGone, key: KEY },
        { file: valid, key: KEY },
      ],
      null,
      2
    )
  );

  const broken = await runChecks({});
  const ledger = check(broken, 'mcp ledger');
  assert.equal(ledger.level, 'warn');
  assert.match(ledger.detail, /codebase-memory-mcp: missing\.json missing/, 'missing file reported');
  assert.match(ledger.detail, /entry gone from opencode\.jsonc/, 'jsonc text check');
  assert.match(ledger.detail, /entry gone from config\.toml/, 'toml text check');
  assert.match(ledger.detail, /broken\.json: parse error — fix before `aio rollback`/, 'unparseable json');
  assert.match(ledger.detail, /entry gone from entry\.json/, 'valid json without the key');
  assert.ok(!/ok\.json/.test(ledger.detail), 'the valid entry is not flagged');

  fs.writeFileSync(LEDGER, JSON.stringify([{ file: valid, key: KEY }], null, 2));
  const healthy = await runChecks({});
  const okLedger = check(healthy, 'mcp ledger');
  assert.equal(okLedger.level, 'ok');
  assert.match(okLedger.detail, /1 aio-added MCP entry file\(s\) present & valid/);

  fs.writeFileSync(LEDGER, '[]');
  const empty = await runChecks({});
  assert.match(check(empty, 'mcp ledger').detail, /0 entries on record — nothing aio-added/);
});

/* ---------------- runDoctor plain (lines 240–245) ---------------- */

test('runDoctor: healthy run → exit 0, summary without the fix hint', async (t) => {
  mockNet(t);
  hermeticHome(t, { withBlock: true });
  fs.writeFileSync(MANIFEST, FRESH_MANIFEST);
  fs.writeFileSync(CONFIG, JSON.stringify({ version: '9.0.0' }));
  fs.writeFileSync(LEDGER, '[]');

  const r = await runDoctor({});

  assert.equal(r.ok, true, r.text);
  assert.equal(r.exit, 0, 'healthy → exit 0');
  assert.match(r.text, /0 issue\(s\), \d+ warning\(s\)/);
  assert.ok(!r.text.includes('aio doctor --fix'), 'no fix hint when ok');
  assert.match(r.text, /^aio doctor — v\d+\.\d+\.\d+ $/m, 'plain header (no mode suffix)');
});

/* ---------------- --fix spawn paths (lines 212–238) ---------------- */

test('runDoctor --fix: spawn failure → "fix failed" note, issues still reported, exit 1', async (t) => {
  mockNet(t);
  hermeticHome(t, { withBlock: true });
  fs.rmSync(MANIFEST, { force: true });
  const origExists = fs.existsSync.bind(fs);
  t.mock.method(fs, 'existsSync', (p) => (/\bbin[\\/]aio\.js$/.test(String(p)) ? false : origExists(p)));
  assert.equal(aioBinPath(), process.execPath, 'hidden bin → aioBinPath falls back to the runtime');

  const r = await runDoctor({ fix: true });

  assert.equal(r.ok, false, 'fix could not run → issues remain');
  assert.equal(r.exit, 1);
  assert.match(r.text, /fix failed: /, 'spawn error surfaced verbatim');
  assert.ok(!r.text.includes('setup re-run complete'), 'no success note on failure');
  assert.match(r.text, /run `aio doctor --fix`/, 'hint still shown');
});

test('runDoctor --fix --json: spawn failure → payload carries fix {attempted, ok:false, error}', async (t) => {
  mockNet(t);
  hermeticHome(t, { withBlock: true });
  fs.rmSync(MANIFEST, { force: true });
  const origExists = fs.existsSync.bind(fs);
  t.mock.method(fs, 'existsSync', (p) => (/\bbin[\\/]aio\.js$/.test(String(p)) ? false : origExists(p)));

  const r = await runDoctor({ fix: true, json: true });

  const p = JSON.parse(r.text);
  assert.equal(p.mode, 'fix', 'fix mode in the payload');
  assert.equal(p.fix.attempted, true, 'the fix was attempted');
  assert.equal(p.fix.ok, false, 'spawn failure → not ok');
  assert.match(String(p.fix.error), /\S/, 'the spawn error is surfaced verbatim');
  assert.equal(r.ok, false, 'issues remain after a failed fix');
  assert.equal(r.exit, 1, 'exit mirrors ok');
});

/** Spawn the real `aio --yes` setup, fully sandboxed: temp state dir (env), temp
 *  home (USERPROFILE/HOME), empty PATH (no external tools reachable). */
function sandboxChild(t, home) {
  const saved = { USERPROFILE: process.env.USERPROFILE, HOME: process.env.HOME };
  process.env.USERPROFILE = home;
  process.env.HOME = home;
  t.after(() => {
    if (saved.USERPROFILE === undefined) delete process.env.USERPROFILE;
    else process.env.USERPROFILE = saved.USERPROFILE;
    if (saved.HOME === undefined) delete process.env.HOME;
    else process.env.HOME = saved.HOME;
  });
}

test('runDoctor --fix: healthy spawn → setup re-run, after-fix report, exit 0', async (t) => {
  mockNet(t, { github: 'fail', ollama: 'fail' });
  const home = hermeticHome(t); // no block, no agent dirs → nothing to inject
  sandboxChild(t, home);
  fs.rmSync(MANIFEST, { force: true });
  fs.rmSync(CONFIG, { force: true });

  const r = await runDoctor({ fix: true });

  assert.match(r.text, /fix: setup re-run complete — re-check:/, 'child setup ran');
  assert.equal(r.ok, true, r.text);
  assert.match(r.text, /after fix: 0 issue\(s\), \d+ warning\(s\)/);
  assert.equal(r.exit, 0);
  assert.ok(fs.existsSync(MANIFEST), 'the child regenerated the manifest in the temp state dir');
});

test('runDoctor --fix --json: healthy spawn → machine payload with mode "fix"', async (t) => {
  mockNet(t, { github: 'fail', ollama: 'fail' });
  const home = hermeticHome(t);
  sandboxChild(t, home);
  fs.rmSync(MANIFEST, { force: true });
  fs.rmSync(CONFIG, { force: true });

  const r = await runDoctor({ fix: true, json: true });

  const p = JSON.parse(r.text);
  assert.equal(p.mode, 'fix', 'fix mode in the payload');
  assert.equal(p.schemaVersion, 1);
  assert.deepEqual(p.fix, { attempted: true, ok: true }, 'machine-readable fix outcome (no error key on success)');
  assert.equal(p.ok, true, `issues: ${p.issues} (${p.checks.filter((c) => c.level === 'bad').map((c) => c.detail).join('; ')})`);
  assert.equal(p.checks.length, 9, 'still exactly 9 checks after a fix');
  assert.equal(r.ok, p.ok, 'r.ok mirrors the payload');
  assert.equal(r.exit, 0, 'exit mirrors ok');
});
