// doctor.test.js — `aio doctor` self-diagnosis (isolated state, all network mocked).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

process.env.AIO_STATE_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-doctor-state-'));
const { runChecks, runDoctor } = await import('../src/doctor.js');
const { STATE_DIR } = await import('../src/paths.js');
const { BLOCK_START, BLOCK_END } = await import('../src/write.js');

const MANIFEST = path.join(STATE_DIR, 'aio-context.md');
const SLIM_MANIFEST = [
  '<!-- AUTO-GENERATED by aio v1.3.0 — do not edit -->',
  '',
  '# AIO Context Manifest',
  '',
  '> **Live architecture — zero storage.** There is no catalog database: `aio ask` searches live.',
  '',
  '## AGENTS DETECTED',
  '',
].join('\n');

/** Mock every outbound HTTP call: github reachable, ollama answered. */
function mockNet(t) {
  return t.mock.method(globalThis, 'fetch', async (input) => {
    const url = String(input instanceof Request ? input.url : input);
    if (url.includes('api.github.com')) return json({ resources: {} });
    if (url.includes('/api/tags')) return json({ models: [{ name: 'qwen3:4b' }] });
    throw new Error(`unexpected network call in test: ${url}`);
  });
}

function json(body) {
  return new Response(JSON.stringify(body), { status: 200, headers: { 'content-type': 'application/json' } });
}

test('runChecks: returns structured checks (levels + ids), never throws', async (t) => {
  const net = mockNet(t);
  fs.rmSync(MANIFEST, { force: true });
  const r = await runChecks({});
  assert.ok(Array.isArray(r.checks) && r.checks.length >= 6, 'at least 6 checks');
  for (const c of r.checks) {
    assert.ok(['ok', 'warn', 'bad'].includes(c.level), `level: ${c.level}`);
    assert.ok(c.id && c.detail !== undefined, 'id + detail present');
    assert.match(c.text, /^\[(ok|~~|!!)\]/, 'tagged line format');
  }
  assert.ok(r.checks.some((c) => c.id === 'node'), 'node check exists');
  assert.ok(r.checks.some((c) => c.id === 'live'), 'live check exists');
  assert.ok(r.checks.some((c) => c.id === 'manifest'), 'manifest check exists');
  assert.ok(r.checks.some((c) => c.id === 'agent blocks'), 'agent blocks check exists');
  assert.equal(typeof r.ok, 'boolean');
  assert.equal(net.mock.callCount(), 2, 'github + ollama probed once each');
});

test('runChecks: fixture state (no manifest) → manifest bad + ok=false', async (t) => {
  mockNet(t);
  fs.rmSync(MANIFEST, { force: true });
  const r = await runChecks({});
  assert.ok(r.issues >= 1);
  assert.ok(r.checks.some((c) => c.id === 'manifest' && c.level === 'bad'));
  assert.ok(!r.checks.some((c) => c.id === 'catalog db'), 'catalog db check dropped (no local catalog)');
  assert.equal(r.ok, false, 'missing manifest must fail');
});

test('runDoctor: report text + exit 1 when issues exist', async (t) => {
  mockNet(t);
  fs.rmSync(MANIFEST, { force: true });
  const r = await runDoctor({});
  assert.match(r.text, /aio doctor/);
  assert.match(r.text, /issue\(s\)/);
  assert.equal(r.exit, 1, 'issues → exit 1');
  assert.equal(r.ok, false);
});

test('runChecks: AIO_OFFLINE=1 + fresh slim manifest → ok=true (deterministic, no network)', async (t) => {
  process.env.AIO_OFFLINE = '1';
  t.after(() => {
    delete process.env.AIO_OFFLINE;
    fs.rmSync(MANIFEST, { force: true });
  });
  t.mock.method(globalThis, 'fetch', async (input) => {
    throw new Error(`network must not be touched in offline mode: ${input}`);
  });
  fs.writeFileSync(MANIFEST, SLIM_MANIFEST); // fresh mtime → not stale
  // Hermetic agent env: temp home whose ~/AGENTS.md carries the block, so
  // globalWanted (hermes/freebuff on the real PATH, or ~/AGENTS.md existing)
  // can never turn the "agent blocks" check into [!!] missing: global.
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-doctor-home-'));
  fs.writeFileSync(path.join(home, 'AGENTS.md'), `${BLOCK_START}\nmocked\n${BLOCK_END}\n`);
  t.mock.method(os, 'homedir', () => home);
  t.after(() => fs.rmSync(home, { recursive: true, force: true }));

  const r = await runChecks({});
  const live = r.checks.find((c) => c.id === 'live');
  assert.equal(live.level, 'ok');
  assert.match(live.text, /AIO_OFFLINE=1/, 'offline is a deterministic ok');
  const manifest = r.checks.find((c) => c.id === 'manifest');
  assert.equal(manifest.level, 'ok');
  assert.match(manifest.text, /live architecture \(no search storage\)/);
  assert.equal(r.issues, 0, r.checks.filter((c) => c.level === 'bad').map((c) => c.text).join('; '));
  assert.equal(r.ok, true);
});
