// status.test.js — self-check for src/status.js (isolated state, temp fixtures).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

process.env.AIO_STATE_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-status-'));
const { blockState, runStatus } = await import('../src/status.js');
const { BLOCK_START, BLOCK_END } = await import('../src/write.js');
const { STATE_DIR } = await import('../src/paths.js');

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-status-fix-'));
const MANIFEST = path.join(STATE_DIR, 'aio-context.md');
const SLIM_MANIFEST = [
  '<!-- AUTO-GENERATED by aio v1.3.0 — do not edit -->',
  '',
  '# AIO Context Manifest',
  '',
  '> **Live architecture — zero storage.** There is no catalog database: `aio ask` searches live.',
  '',
  '## AGENTS DETECTED',
  '',
].join('\n');

test('blockState: missing / no block / injected', () => {
  assert.equal(blockState(path.join(tmp, 'nope.md')), 'missing');
  const plain = path.join(tmp, 'plain.md');
  fs.writeFileSync(plain, '# docs\n');
  assert.equal(blockState(plain), 'no block');
  const wired = path.join(tmp, 'wired.md');
  fs.writeFileSync(wired, `# docs\n${BLOCK_START}\nhello\n${BLOCK_END}\n`);
  assert.equal(blockState(wired), 'injected');
});

test('runStatus: healthy — fresh slim live manifest in STATE_DIR + repos dir', (t) => {
  t.mock.method(console, 'log', () => {}); // keep test output clean
  fs.writeFileSync(MANIFEST, SLIM_MANIFEST); // fresh mtime → not stale
  t.after(() => fs.rmSync(MANIFEST, { force: true }));

  const repos = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-status-repos-'));
  fs.mkdirSync(path.join(repos, 'alpha'));
  fs.mkdirSync(path.join(repos, 'beta'));
  fs.mkdirSync(path.join(repos, '.git'));

  const r = runStatus({ repos });
  const out = r.lines.join('\n');
  const manifestLine = r.lines.find((l) => l.startsWith('manifest'));
  assert.ok(manifestLine && manifestLine.includes(MANIFEST), `manifest line points at ${MANIFEST}`);
  assert.match(out, /live architecture \(no search storage\)/, 'slim manifest → live architecture line');
  assert.match(out, /\(2 dirs\)/, 'non-dot dirs counted, .git skipped');
  assert.ok(!r.issues.some((i) => i.includes('manifest')), r.issues.join('; '));
  assert.equal(r.ok, true, r.issues.join('; '));
});

test('runStatus: manifest missing → issue reported', (t) => {
  t.mock.method(console, 'log', () => {});
  fs.rmSync(MANIFEST, { force: true });

  const r = runStatus({});
  assert.match(r.lines.join('\n'), /manifest\s+MISSING/);
  assert.ok(r.issues.some((i) => i.includes('manifest')), r.issues.join('; '));
  assert.equal(r.ok, false);
});

test('runStatus: legacy manifest (no live marker) → issue reported', (t) => {
  t.mock.method(console, 'log', () => {});
  fs.writeFileSync(MANIFEST, '# ctx\n## REPOS (3)\n');
  t.after(() => fs.rmSync(MANIFEST, { force: true }));

  const r = runStatus({});
  const out = r.lines.join('\n');
  assert.match(out, /legacy layout/);
  assert.ok(r.issues.some((i) => i.includes('legacy')), r.issues.join('; '));
  assert.equal(r.ok, false);
});
