// status.test.js — self-check for src/status.js (isolated state, temp fixtures).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

process.env.AIO_STATE_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-status-'));
const { blockState, runStatus } = await import('../src/status.js');
const { BLOCK_START, BLOCK_END } = await import('../src/write.js');
const { STATE_DIR } = await import('../src/paths.js');

const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-status-fix-'));
const MANIFEST = path.join(STATE_DIR, 'aio-context.md');
const SLIM_MANIFEST = [
  '<!-- AUTO-GENERATED by aio v1.3.0 — do not edit -->',
  '',
  '# AIO Context Manifest',
  '',
  '> **Live architecture — zero storage.** There is no catalog database: `aio ask` searches live.',
  '',
  '## AGENTS DETECTED',
  '',
].join('\n');

/**
 * Isolated home for runStatus — blockTargets must see ONLY fixture state, never
 * the real machine: temp dir, inert PATH (detectAgents finds no hermes/freebuff
 * → globalWanted false → no global target), APPDATA pointed at an absent dir
 * (win32 zed target → n/a). Every target lands on the n/a path: missing file +
 * config dir absent → no issue (src/status.js), so ok===true is machine-independent.
 */
function mockHome(t) {
  const home = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-status-home-'));
  const savedPath = process.env.PATH;
  const savedAppData = process.env.APPDATA;
  process.env.PATH = '';
  process.env.APPDATA = path.join(home, 'AppData', 'Roaming'); // absent on purpose → zed n/a
  t.mock.method(os, 'homedir', () => home);
  t.after(() => {
    if (savedPath === undefined) delete process.env.PATH;
    else process.env.PATH = savedPath;
    if (savedAppData === undefined) delete process.env.APPDATA;
    else process.env.APPDATA = savedAppData;
    fs.rmSync(home, { recursive: true, force: true });
  });
  return home;
}

test('blockState: missing / no block / injected', () => {
  assert.equal(blockState(path.join(tmp, 'nope.md')), 'missing');
  const plain = path.join(tmp, 'plain.md');
  fs.writeFileSync(plain, '# docs\n');
  assert.equal(blockState(plain), 'no block');
  const wired = path.join(tmp, 'wired.md');
  fs.writeFileSync(wired, `# docs\n${BLOCK_START}\nhello\n${BLOCK_END}\n`);
  assert.equal(blockState(wired), 'injected');
});

test('runStatus: healthy — fresh slim live manifest in STATE_DIR', (t) => {
  t.mock.method(console, 'log', () => {}); // keep test output clean
  mockHome(t); // scan the isolated fixture home, never the real one
  fs.writeFileSync(MANIFEST, SLIM_MANIFEST); // fresh mtime → not stale
  t.after(() => fs.rmSync(MANIFEST, { force: true }));

  const r = runStatus({});
  const out = r.lines.join('\n');
  const manifestLine = r.lines.find((l) => l.startsWith('manifest'));
  assert.ok(manifestLine && manifestLine.includes(MANIFEST), `manifest line points at ${MANIFEST}`);
  assert.match(out, /live architecture \(no search storage\)/, 'slim manifest → live architecture line');
  assert.match(out, /agents/, 'agents section present');
  // every target in the fixture home is fresh/missing with its config dir
  // absent → the n/a path (never a bare gap, never an issue)
  for (const label of ['opencode', 'claude', 'kimi', 'jcode', 'codex', 'gemini', 'zed']) {
    assert.match(out, new RegExp(`^  ${label}\\s+n/a\\b`, 'm'), `${label}: absent in fixture home → n/a`);
  }
  assert.ok(!r.issues.length, r.issues.join('; '));
  assert.equal(r.ok, true, r.issues.join('; '));
});

test('runStatus: manifest missing → issue reported', (t) => {
  t.mock.method(console, 'log', () => {});
  mockHome(t);
  fs.rmSync(MANIFEST, { force: true });

  const r = runStatus({});
  assert.match(r.lines.join('\n'), /manifest\s+MISSING/);
  assert.ok(r.issues.some((i) => i.includes('manifest')), r.issues.join('; '));
  assert.equal(r.ok, false);
});

test('runStatus: legacy manifest (no live marker) → issue reported', (t) => {
  t.mock.method(console, 'log', () => {});
  mockHome(t);
  fs.writeFileSync(MANIFEST, '# ctx\n## REPOS (3)\n');
  t.after(() => fs.rmSync(MANIFEST, { force: true }));

  const r = runStatus({});
  const out = r.lines.join('\n');
  assert.match(out, /legacy layout/);
  assert.ok(r.issues.some((i) => i.includes('legacy')), r.issues.join('; '));
  assert.equal(r.ok, false);
});
