// v150.test.js — v1.5.0 regression coverage: consent gate (src/consent.js),
// shared target list (src/targets.js), block drift C-02 (src/write.js),
// `aio init` (src/init.js), status hand-edit reporting (src/status.js),
// ask ok-invariant B-01 (src/search.js), doctor 9-check report (src/doctor.js).
// Isolated state + temp fixtures — never ~/.aio, never the real user home.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

process.env.AIO_STATE_DIR = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-v150-')); // state/backups/hashes → temp dir (must precede src imports)
process.env.AIO_NO_GH = '1'; // no gh subprocess in tests
process.env.AIO_NO_AI = '1'; // deterministic: no Ollama rerank

const { decide, gatedRun } = await import('../src/consent.js');
const { blockTargets, zedTarget, globalWanted } = await import('../src/targets.js');
const { injectBlock, stripBlock, blockEdited, currentBlock, buildBlock, BLOCK_START, BLOCK_END } = await import(
  '../src/write.js'
);
const { STATE_DIR, BACKUP_DIR } = await import('../src/paths.js');
const { runInit } = await import('../src/init.js');
const { runStatus } = await import('../src/status.js');
const { runAsk } = await import('../src/search.js');
const { runDoctor } = await import('../src/doctor.js');

/** Fresh temp home dir (targets/globalWanted never touch the real one). */
function tempHome() {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'aio-v150-home-'));
}

/** Fresh temp fixture file with the given content. */
function fixture(prefix, name, content) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), prefix));
  const file = path.join(dir, name);
  fs.writeFileSync(file, content);
  return file;
}

function backupCount() {
  return fs.existsSync(BACKUP_DIR) ? fs.readdirSync(BACKUP_DIR).length : 0;
}

/** Rewrite `file` with `from` → `to` swapped INSIDE its marker block. */
function handEdit(file, from, to) {
  const txt = fs.readFileSync(file, 'utf8');
  assert.ok(txt.includes(from), `fixture contains ${from}`);
  assert.ok(
    txt.indexOf(from) > txt.indexOf(BLOCK_START) && txt.indexOf(from) < txt.indexOf(BLOCK_END),
    'edit lands inside the marker block'
  );
  fs.writeFileSync(file, txt.replace(from, to));
}

const SLIM_MANIFEST = [
  '<!-- AUTO-GENERATED by aio v1.5.0 — do not edit -->',
  '',
  '# AIO Context Manifest',
  '',
  '> **Live architecture — zero storage.** There is no catalog database: `aio ask` searches live.',
  '',
  '## AGENTS DETECTED',
  '',
].join('\n');

/* ---------------- 1. src/consent.js ---------------- */

test('decide: dry/preview → dry, yes → write, interactive → plan-ask, else plan-stop', () => {
  assert.equal(decide({}), 'plan-stop');
  assert.equal(decide({ dry: true }), 'dry');
  assert.equal(decide({ preview: true }), 'dry');
  assert.equal(decide({ yes: true }), 'write');
  assert.equal(decide({ interactive: true }), 'plan-ask');
  // precedence: plan-only beats consent, consent beats the prompt
  assert.equal(decide({ dry: true, yes: true }), 'dry');
  assert.equal(decide({ preview: true, yes: true }), 'dry');
  assert.equal(decide({ yes: true, interactive: true }), 'write');
  assert.equal(decide({ dry: true, preview: true, yes: true, interactive: true }), 'dry');
});

test('gatedRun: dry → showPlan only, returns plan, apply never called', async () => {
  const calls = [];
  const r = await gatedRun({
    dry: true,
    showPlan: (preview) => calls.push(['plan', preview]),
    apply: () => calls.push(['apply']),
  });
  assert.equal(r, 'plan');
  assert.deepEqual(calls, [['plan', false]], 'showPlan(preview) once, apply skipped');
});

test('gatedRun: dry beats yes; showPlan receives the preview flag', async () => {
  const calls = [];
  const r = await gatedRun({
    dry: true,
    yes: true,
    preview: true,
    showPlan: (preview) => calls.push(['plan', preview]),
    apply: () => calls.push(['apply']),
  });
  assert.equal(r, 'plan');
  assert.deepEqual(calls, [['plan', true]], 'preview passed through, apply skipped');
});

test('gatedRun: yes → apply called, returns applied, showPlan skipped', async () => {
  const calls = [];
  const r = await gatedRun({
    yes: true,
    showPlan: () => calls.push(['plan']),
    apply: () => calls.push(['apply']),
  });
  assert.equal(r, 'applied');
  assert.deepEqual(calls, [['apply']], 'only apply runs (TTY-independent branch)');
});

/* ---------------- 2. src/targets.js ---------------- */

test('blockTargets: 7 agent targets in order, every path absolute, no global by default', () => {
  const home = tempHome();
  const list = blockTargets(home, { agents: [] }); // explicit [] → globalWanted never scans the real machine

  assert.deepEqual(
    list.map((t) => t.label),
    ['opencode', 'claude', 'kimi', 'jcode', 'codex', 'gemini', 'zed'],
    'AGENT_INSTRUCTIONS order + zed, no global'
  );
  for (const t of list) {
    assert.ok(path.isAbsolute(t.file), `${t.label}: file absolute (${t.file})`);
    assert.ok(path.isAbsolute(t.dir), `${t.label}: dir absolute (${t.dir})`);
    assert.ok(t.file.startsWith(t.dir + path.sep), `${t.label}: file inside dir`);
  }
  const opencode = list.find((t) => t.label === 'opencode');
  assert.equal(opencode.file, path.join(home, '.config', 'opencode', 'AGENTS.md'));
  assert.equal(opencode.dir, path.join(home, '.config', 'opencode'));
});

test('blockTargets: global only with global:"always" or globalWanted(home, agents)', () => {
  const home = tempHome();
  assert.equal(
    blockTargets(home, { agents: [] }).some((t) => t.label === 'global'),
    false,
    'auto + no ~/AGENTS.md + no hermes/freebuff → no global'
  );

  const always = blockTargets(home, { agents: [], global: 'always' }).find((t) => t.label === 'global');
  assert.ok(always, "global:'always' → global present");
  assert.equal(always.file, path.join(home, 'AGENTS.md'));
  assert.equal(always.dir, home);

  fs.writeFileSync(path.join(home, 'AGENTS.md'), '# rules\n');
  const auto = blockTargets(home, { agents: [] }).filter((t) => t.label === 'global');
  assert.equal(auto.length, 1, 'existing ~/AGENTS.md → exactly one global entry');

  const home2 = tempHome();
  assert.ok(blockTargets(home2, { agents: [{ name: 'hermes', found: true }] }).some((t) => t.label === 'global'));
  assert.ok(blockTargets(home2, { agents: [{ name: 'freebuff', found: true }] }).some((t) => t.label === 'global'));
  assert.equal(
    blockTargets(home2, { agents: [{ name: 'opencode', found: true }] }).some((t) => t.label === 'global'),
    false,
    'a non-hermes/freebuff agent does not pull in global'
  );
});

test('globalWanted: true on existing ~/AGENTS.md or found hermes/freebuff, else false', () => {
  const home = tempHome();
  assert.equal(globalWanted(home, []), false, 'no file + no hermes/freebuff');

  fs.writeFileSync(path.join(home, 'AGENTS.md'), '# rules\n');
  assert.equal(globalWanted(home, []), true, 'AGENTS.md exists');

  const bare = tempHome();
  assert.equal(globalWanted(bare, [{ name: 'hermes', found: true }]), true);
  assert.equal(globalWanted(bare, [{ name: 'freebuff', found: true }]), true);
  assert.equal(globalWanted(bare, [{ name: 'hermes', found: false }]), false, 'detected-but-absent ≠ found');
  assert.equal(globalWanted(bare, [{ name: 'claude', found: true }]), false);
});

test('zedTarget: platform branch — win32 %APPDATA%\\Zed, posix ~/.config/zed', () => {
  const home = tempHome();
  const z = zedTarget(home);
  assert.equal(z.label, 'zed');
  if (process.platform === 'win32') {
    const dir = path.join(process.env.APPDATA || path.join(home, 'AppData', 'Roaming'), 'Zed');
    assert.equal(z.dir, dir, 'win32 dir = %APPDATA%\\Zed (fallback home\\AppData\\Roaming\\Zed)');
  } else {
    assert.equal(z.dir, path.join(home, '.config', 'zed'));
  }
  assert.equal(z.file, path.join(z.dir, 'AGENTS.md'));
  assert.ok(path.isAbsolute(z.dir) && path.isAbsolute(z.file));
});

/* ---------------- 3. src/write.js drift detection (C-02) ---------------- */

test('blockEdited: false right after injectBlock, true after hand-edit inside markers', () => {
  const file = fixture('aio-v150-drift-', 'AGENTS.md', '# my rules\n');
  assert.equal(injectBlock(file, 'BODY-v1', 'drift').status, 'injected');
  assert.equal(blockEdited(file), false, 'just written → no drift');

  handEdit(file, 'BODY-v1', 'BODY-v1 + my tweak');
  assert.equal(blockEdited(file), true, 'content inside markers changed → drift');
  assert.ok(fs.readFileSync(file, 'utf8').includes('my tweak'), 'hand edit persisted');
});

test('injectBlock dry on hand-edited file → would update (hand-edit detected), writes nothing', () => {
  const file = fixture('aio-v150-drydrift-', 'AGENTS.md', '# my rules\n');
  injectBlock(file, 'BODY', 't');
  handEdit(file, 'BODY', 'BODY hacked');
  const before = fs.readFileSync(file, 'utf8');
  const n0 = backupCount();

  const r = injectBlock(file, 'BODY v2', 't', { dry: true });

  assert.match(r.status, /would update \(hand-edit detected\)/);
  assert.equal(fs.readFileSync(file, 'utf8'), before, 'dry run leaves the hand edit untouched');
  assert.equal(backupCount(), n0, 'no backup on dry run');
  assert.equal(blockEdited(file), true, 'drift still reported');
});

test('injectBlock real on hand-edited file → hand-edit replaced, backup kept, drift cleared', () => {
  const file = fixture('aio-v150-replace-', 'AGENTS.md', '# my rules\n');
  injectBlock(file, 'BODY-v1', 't');
  handEdit(file, 'BODY-v1', 'BODY-v1 hacked');
  const n0 = backupCount();

  const r = injectBlock(file, 'BODY-v2', 't');

  assert.match(r.status, /hand-edit replaced/);
  assert.match(r.status, /kept in backups\//);
  assert.equal(backupCount(), n0 + 1, 'hand-edited version kept in backups/ first');
  assert.ok(fs.readFileSync(file, 'utf8').includes('BODY-v2'), 'fresh block landed');
  assert.equal(blockEdited(file), false, 'hash refreshed → drift cleared');
});

test('stripBlock: prunes the stored hash — block gone, blockEdited false', () => {
  const file = fixture('aio-v150-strip-', 'AGENTS.md', '# my rules\n');
  injectBlock(file, 'BODY', 't');
  handEdit(file, 'BODY', 'BODY hacked');
  assert.equal(blockEdited(file), true, 'precondition: drifted');

  assert.equal(stripBlock(file), 'removed');

  assert.equal(currentBlock(file), null, 'block gone from the file');
  assert.equal(blockEdited(file), false, 'no block → no drift');
  const stored = JSON.parse(fs.readFileSync(path.join(STATE_DIR, 'block-hashes.json'), 'utf8'));
  assert.equal(stored[path.resolve(file)], undefined, 'stale drift entry pruned from block-hashes.json');
});

/* ---------------- 3b. src/write.js buildBlock manifest pointer (W4) ---------------- */

test('buildBlock: manifestPath null/omitted → NO "Context manifest" line, header + rules kept', () => {
  for (const manifestPath of [null, undefined]) {
    const b = buildBlock({ version: '1.5.0', manifestPath });
    const tag = `manifestPath=${manifestPath}`;
    assert.ok(!b.includes('Context manifest'), `${tag}: no dangling pointer line`);
    assert.equal(b.split('Context manifest').length - 1, 0, `${tag}: pointer count is zero`);
    assert.ok(b.startsWith('### AIO AUTO-CONTEXT (generated by aio v1.5.0'), `${tag}: header kept`);
    assert.ok(b.includes('Auto-use rules (plain-language prompts only'), `${tag}: rules header kept`);
    assert.ok(b.includes('[aio] Using [<name>](<url>) (<type>) — <function>'), `${tag}: disclosure rule kept`);
    assert.ok(b.includes('6. Reply in the user’s language.'), `${tag}: all 6 rules kept`);
  }
});

test('buildBlock: manifestPath set → pointer line present exactly once, header + rules intact', () => {
  const mp = path.join(STATE_DIR, 'aio-context.md');
  const b = buildBlock({ version: '1.5.0', manifestPath: mp });

  assert.ok(b.startsWith('### AIO AUTO-CONTEXT (generated by aio v1.5.0'), 'header first line');
  assert.equal(b.split(`- Context manifest (auto-generated): \`${mp}\``).length - 1, 1, 'pointer line exactly once');
  assert.equal(b.split('Context manifest').length - 1, 1, 'no second mention anywhere in the block');
  assert.ok(b.includes('Auto-use rules (plain-language prompts only'), 'rules header kept');
  // pointer sits between header and rules (line 3 after the blank separator)
  assert.ok(b.indexOf('Context manifest') < b.indexOf('Auto-use rules'), 'pointer precedes the rules');
});

/* ---------------- 4. src/init.js ---------------- */

test('runInit dry run: creates nothing in cwd', async (t) => {
  t.mock.method(console, 'log', () => {});
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-v150-init-dry-'));
  const prev = process.cwd();
  try {
    process.chdir(cwd);
    await runInit({ dryRun: true });
    assert.equal(fs.existsSync(path.join(cwd, 'AGENTS.md')), false, 'no AGENTS.md written');
    assert.equal(fs.existsSync(path.join(cwd, '.github')), false, 'no .github written');
  } finally {
    process.chdir(prev);
  }
});

test('runInit write: AGENTS.md with markers + AIO AUTO-CONTEXT; rerun → unchanged', async (t) => {
  const logs = [];
  t.mock.method(console, 'log', (...a) => logs.push(a.join(' ')));
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-v150-init-'));
  const prev = process.cwd();
  try {
    process.chdir(cwd);
    await runInit({});

    const file = path.join(cwd, 'AGENTS.md');
    assert.ok(fs.existsSync(file), 'AGENTS.md created');
    const first = fs.readFileSync(file, 'utf8');
    assert.ok(first.includes(BLOCK_START), 'block start marker present');
    assert.ok(first.includes(BLOCK_END), 'block end marker present');
    assert.ok(first.includes('AIO AUTO-CONTEXT'), 'auto-context heading present');

    await runInit({});
    assert.equal(fs.readFileSync(file, 'utf8'), first, 'second run leaves content byte-identical');
    assert.ok(
      logs.some((l) => /AGENTS\.md\s+unchanged/.test(l)),
      `second run status line reports unchanged:\n${logs.join('\n')}`
    );
  } finally {
    process.chdir(prev);
  }
});

test('runInit --copilot: pointer file links AGENTS.md, block marker absent', async (t) => {
  t.mock.method(console, 'log', () => {});
  const cwd = fs.mkdtempSync(path.join(os.tmpdir(), 'aio-v150-init-cop-'));
  const prev = process.cwd();
  try {
    process.chdir(cwd);
    await runInit({ copilot: true });

    const agentsFile = path.join(cwd, 'AGENTS.md');
    const copilotFile = path.join(cwd, '.github', 'copilot-instructions.md');
    assert.ok(fs.existsSync(agentsFile), 'AGENTS.md created');
    assert.ok(fs.existsSync(copilotFile), 'copilot file created');
    assert.ok(fs.readFileSync(agentsFile, 'utf8').includes(BLOCK_START), 'AGENTS.md carries the block');

    const copilot = fs.readFileSync(copilotFile, 'utf8');
    assert.match(copilot, /\[AGENTS\.md\]\(\.\.\/AGENTS\.md\)/, 'pointer link to ../AGENTS.md');
    assert.ok(!copilot.includes(BLOCK_START) && !copilot.includes(BLOCK_END), 'no block markers in copilot file');
    assert.equal(copilot.split(BLOCK_START).length - 1, 0, 'full block NOT duplicated (M-04)');
  } finally {
    process.chdir(prev);
  }
});

/* ---------------- 5. src/status.js — hand-edit reporting (C-02) ---------------- */

test('runStatus: hand-edited block → issue "edited by hand", ok=false', (t) => {
  t.mock.method(console, 'log', () => {}); // keep test output clean
  fs.writeFileSync(path.join(STATE_DIR, 'aio-context.md'), SLIM_MANIFEST); // fresh manifest → not an issue

  const home = tempHome();
  const file = path.join(home, '.config', 'opencode', 'AGENTS.md');
  fs.mkdirSync(path.dirname(file), { recursive: true });
  assert.equal(injectBlock(file, 'BODY-v1', 'status-drift').status, 'injected');
  t.mock.method(os, 'homedir', () => home); // runStatus scans the temp home, never the real one

  const before = runStatus({});
  assert.ok(
    !before.issues.some((i) => /edited by hand/.test(i)),
    `baseline free of drift: ${before.issues.join('; ')}`
  );

  handEdit(file, 'BODY-v1', 'BODY-v1 tweaked by user');

  const after = runStatus({});
  assert.equal(after.ok, false, `hand edit must surface: ${after.issues.join('; ')}`);
  assert.ok(
    after.issues.some((i) => /edited by hand/.test(i)),
    `expected hand-edit issue, got: ${after.issues.join('; ')}`
  );
  assert.ok(after.lines.some((l) => l.includes('injected*')), 'target line marked injected*');
  assert.ok(after.lines.some((l) => l.includes('stale')), 'stale note printed');
});

/* ---------------- 6. src/search.js — ok invariant (B-01) ---------------- */

test('runAsk: AIO_OFFLINE=1 + json → ok=false, offline message, no network', async (t) => {
  process.env.AIO_OFFLINE = '1';
  t.after(() => delete process.env.AIO_OFFLINE);
  t.mock.method(globalThis, 'fetch', async (input) => {
    throw new Error(`offline mode must not fetch: ${input}`);
  });

  const r = await runAsk({ query: 'anything', json: true });

  assert.equal(r.ok, false, 'offline → not ok');
  assert.equal(r.json, null, 'offline early-return carries no json payload');
  assert.match(r.text, /offline \(AIO_OFFLINE=1\)/);
});

test('runAsk: every source fails → sources=[] + errors present → ok=false (B-01 rule)', async (t) => {
  t.mock.method(globalThis, 'fetch', async () => {
    throw new Error('fetch failed: ECONNREFUSED');
  });

  const r = await runAsk({ query: 'csv toolkit', json: true });

  assert.equal(r.ok, false, 'empty sources + errors → ok false');
  assert.deepEqual(r.json.sources, [], 'no source answered');
  assert.ok(r.json.errors.length > 0, `failures surfaced, got: ${JSON.stringify(r.json.errors)}`);
  // the documented rule: ok = sources.length > 0 || errors.length === 0
  assert.equal(
    r.json.sources.length > 0 || r.json.errors.length === 0,
    false,
    'invariant holds for this payload'
  );
  assert.equal(r.json.count, 0);
  assert.equal(r.json.stored, 0, 'zero storage even on failure');
});

/* ---------------- 7. src/doctor.js — 9-check report ---------------- */

test('runDoctor --check: exactly 9 tagged check lines — one per expected label, in runChecks order', async (t) => {
  process.env.AIO_OFFLINE = '1';
  t.after(() => delete process.env.AIO_OFFLINE);
  t.mock.method(globalThis, 'fetch', async (input) => {
    throw new Error(`no network in doctor test: ${input}`);
  }); // offline skips github; mocked fetch makes the ollama probe fail deterministically
  fs.writeFileSync(path.join(STATE_DIR, 'aio-context.md'), SLIM_MANIFEST);

  const r = await runDoctor({ check: true });

  assert.equal(typeof r.text, 'string');
  const tagged = r.text.split('\n').filter((l) => /^\[(ok|~~|!!)\] /.test(l));
  assert.equal(tagged.length, 9, `expected exactly 9 check lines:\n${r.text}`);
  // `${tag} ${id.padEnd(14)} ${detail}` → id occupies chars 5..18 after the 4-char tag
  const ids = tagged.map((l) => l.slice(5, 19).trim());
  const expected = [
    'node',
    'state',
    'live',
    'manifest',
    'agent blocks',
    'agents',
    'gh auth',
    'ollama',
    'mcp ledger',
  ];
  assert.deepEqual([...ids].sort(), [...expected].sort(), 'exactly one line per expected label');
  assert.deepEqual(ids, expected, 'labels printed in runChecks order (one per label, none swapped/dropped)');
  assert.ok([0, 1].includes(r.exit), `exit is 0|1, got ${r.exit}`);
  assert.equal(r.exit, r.ok ? 0 : 1, 'exit mirrors ok');
});
