// init.js — `aio init`: project-level wiring via the OFFICIAL standards:
//   ./AGENTS.md              → read by Zed, Copilot (AGENTS.md support), Cursor, …
//   .github/copilot-instructions.md (--copilot) → official Copilot repo mechanism
// The copilot file carries a short POINTER (no duplicated rules — M-04 discipline),
// so editors reading both files never see the rules twice. Same consent gate as
// setup: TTY → plan + y/N; non-TTY → plan only; --yes writes.
import fs from 'node:fs';
import path from 'node:path';
import { buildBlock, injectBlock, backup } from './write.js';
import { STATE_DIR } from './paths.js';
import { getVersion } from './banner.js';

function pointerBody() {
  return [
    '# Project agent instructions (aio)',
    '',
    'Read [AGENTS.md](../AGENTS.md) first — the `AIO AUTO-CONTEXT` block inside it is the',
    'single source of truth (live `aio ask` search across GitHub/npm/crates, zero storage,',
    'the mandatory `[aio]` disclosure line). Apply its rules to every reply here too.',
    '',
    '_(Generated by `aio init --copilot`; re-run `aio init --copilot` to refresh.)_',
  ].join('\n');
}

export async function runInit(opts = {}) {
  const version = getVersion();
  const dry = !!opts.dryRun;
  const cwd = process.cwd();
  const manifestPath = path.join(STATE_DIR, 'aio-context.md');
  // pointer line only when the manifest actually exists — project-only users
  // (never ran global `aio`) must not get a dangling path (W4)
  const body = buildBlock({ version, manifestPath: fs.existsSync(manifestPath) ? manifestPath : null });

  const results = [];
  const agentsFile = path.join(cwd, 'AGENTS.md');
  results.push({ label: 'AGENTS.md', ...injectBlock(agentsFile, body, 'init-agents', { dry }) });

  if (opts.copilot) {
    const copilotFile = path.join(cwd, '.github', 'copilot-instructions.md');
    const existed = fs.existsSync(copilotFile);
    if (dry) {
      results.push({ label: '.github/copilot-instructions.md', status: existed ? 'would update (dry-run; existing content backed up on write)' : 'would inject (dry-run)', file: copilotFile });
    } else {
      const dir = path.dirname(copilotFile);
      const cur = existed ? fs.readFileSync(copilotFile, 'utf8') : '';
      const next = pointerBody() + '\n';
      if (cur !== next) {
        fs.mkdirSync(dir, { recursive: true });
        // never destroy pre-existing team content silently (F1) — copy first, then replace
        if (existed) backup(copilotFile, 'init-copilot');
        fs.writeFileSync(copilotFile, next);
        results.push({ label: '.github/copilot-instructions.md', status: existed ? 'updated (pointer; previous backed up)' : 'injected (pointer)', file: copilotFile });
      } else {
        results.push({ label: '.github/copilot-instructions.md', status: 'unchanged', file: copilotFile });
      }
    }
  }

  /* ---- report ---- */
  console.log('');
  console.log(`aio init v${version}${dry ? ' — DRY RUN (nothing written)' : ''} — project scope: ${cwd}`);
  console.log('─'.repeat(76));
  console.log('\nProject instruction files (official standards: AGENTS.md · copilot-instructions.md)');
  for (const r of results) {
    const tag = /error/i.test(r.status) ? '!' : /skip/i.test(r.status) ? ' ' : 'x';
    console.log(`  [${tag}] ${r.label.padEnd(26)} ${r.status} — ${r.file}`);
  }
  console.log('');
  if (dry) {
    console.log('Dry run complete — nothing written. Re-run with --yes (or confirm) to apply, then commit the files.');
  } else {
    console.log('Done. Commit AGENTS.md'+(opts.copilot ? ' + .github/copilot-instructions.md' : '')+' so every teammate\'s agent inherits the same rules.');
    console.log('Reminder: `aio` (global) wires your machine; `aio init` wires THIS repo.');
  }
  console.log('');
}
