// write.js — backups, block injection, context manifest, MCP ensure, path repair
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { BACKUP_DIR, STATE_DIR } from './paths.js';

export const BLOCK_START = '<!-- aio:auto-config:v1:start -->';
export const BLOCK_END = '<!-- aio:auto-config:v1:end -->';
const BLOCK_RE = /<!-- aio:auto-config:v1:start -->[\s\S]*?<!-- aio:auto-config:v1:end -->/;

export function backup(file, label) {
  if (!fs.existsSync(file)) return null;
  fs.mkdirSync(BACKUP_DIR, { recursive: true });
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const safe = String(label).replace(/[^a-z0-9_-]/gi, '_');
  const dest = path.join(BACKUP_DIR, `${safe}__${ts}__${path.basename(file)}`);
  fs.copyFileSync(file, dest);
  return dest;
}

/** Build the auto-use rule block (FR2 + FR6: usage disclosure format). */
export function buildBlock({ version, manifestPath, dataDir }) {
  const lines = [
    `### AIO AUTO-CONTEXT (generated by aio v${version} — do not edit; re-run \`aio\` to refresh)`,
    '',
    `- Context manifest (auto-generated): \`${manifestPath}\``,
    '',
    'Auto-use rules (plain-language prompts only — NO slash-commands required):',
    '1. USAGE DISCLOSURE (mandatory — every reply that draws on the manifest): your FIRST line must be',
    '   [aio] Using [<name>](<url>) (<type>) — <function>',
    '   where [<name>](<url>) = markdown link to the entry\'s URL (plain name if none), <type> = repo | cli | service | skill | site, <function> = its one-line description. Example: [aio] Using [Stirling-PDF](https://github.com/Stirling-Tools/Stirling-PDF) (repo) — HTML/CSS/JS to PDF converter.',
    '   Self-check before sending: did this answer draw on the manifest? If yes and line 1 is not the disclosure → rewrite so it is. Never move/shorten/skip it, even for short answers — without it the response is invalid.',
    '2. PROMPT → LIVE SEARCH → USE → REPORT (every agent, no exceptions):',
    '   a. Prompt needs a repo/tool/skill → run `aio ask "<prompt words>"` FIRST — it searches LIVE (GitHub 630M+ repos + public skills, npm, crates), adaptive to your intent, ZERO storage: results are never saved anywhere.',
    '   b. Websites/URLs → use your own built-in web search (automatic, no key needed). aio ask covers code sources; not-in-ask is never a dead end.',
    '   c. Need the files locally → `aio borrow --get <owner/repo>` (temp clone, 24h TTL), `npx`/`uvx` — never permanent installs or bulk downloads.',
    '   d. Final report lists WHAT CHANGED + EVERY repo/tool/site used as a markdown link with its one-line function, e.g. `- [[d3](https://github.com/d3/d3)] — chart library, rendered the bar chart`.',
    '   e. When done, run `aio borrow --clean`.',
    '3. Prompt involves a local repo/tool/service/skill → route yourself; never ask the user to type `/command`.',
    '4. Prefer already-installed/local things over proposing new installs.',
    '5. The catalog is unlimited because it is live — never claim "not available"; re-query with better keywords instead.',
    '6. Reply in the user’s language.'
  ];
  return lines.join('\n');
}

/** Idempotent marker injection: first run appends, later runs replace in place.
 *  opts.dry → compute the planned status only; no backup, no write (FR12 dry-run). */
export function injectBlock(file, body, label, { dry = false } = {}) {
  const existed = fs.existsSync(file);
  const current = existed ? fs.readFileSync(file, 'utf8') : '';
  const had = BLOCK_RE.test(current);
  const block = `${BLOCK_START}\n${body}\n${BLOCK_END}`;
  const next = had
    ? current.replace(BLOCK_RE, block)
    : (current ? current.replace(/\s*$/, '\n\n') : '') + block + '\n';
  if (next === current) return { status: 'unchanged', file };
  if (dry) return { status: had ? 'would update (dry-run)' : 'would inject (dry-run)', file };
  if (existed) backup(file, label);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, next);
  return { status: had ? 'updated' : 'injected', file };
}

/** Surgically remove the block (rollback, FR7). Returns 'removed' | 'absent'. */
export function stripBlock(file) {
  if (!fs.existsSync(file)) return 'absent';
  const current = fs.readFileSync(file, 'utf8');
  if (!BLOCK_RE.test(current)) return 'absent';
  backup(file, 'rollback');
  const next = current.replace(BLOCK_RE, '').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
  fs.writeFileSync(file, next);
  return 'removed';
}

/** Generate the slim context manifest (FR3 + FR11): rules + disclosure + agents. No catalog data — the catalog is live. */
export function genContext({ version, agents }, outPath) {
  const now = new Date().toISOString();
  const L = [
    `<!-- AUTO-GENERATED by aio v${version} on ${now} — do not edit; run \`aio\` to refresh -->`,
    '',
    '# AIO Context Manifest',
    '',
    '> **Live architecture — zero search storage.** There is no catalog database: `aio ask` searches GitHub (630M+ repos + public skills), npm (3M+ packages) and crates (340K+) in real time, adaptively. Websites are covered by your own web search. Search results are printed and discarded — **no search history is kept**. (aio does write its own files: this manifest, one block per agent, timestamped backups under `~/.aio/backups/`.)',
    '>',
    '> **MANDATORY disclosure** — the moment your answer uses ANY entry surfaced through aio (read, listed, cited, or recommended), START your reply with this exact line:',
    '>',
    '> `[aio] Using [<name>](<url>) (<type>) — <function>`',
    '>',
    '> where `[<name>](<url>)` is a Markdown link to that entry\'s URL, `<type>` = repo | cli | service | skill | site, `<function>` = its one-line description. Example first line: `[aio] Using [Stirling-PDF](https://github.com/Stirling-Tools/Stirling-PDF) (repo) — HTML/CSS/JS to PDF converter`. Self-check before sending: if this answer draws on aio-surfaced entries and line 1 is not the `[aio]` line → rewrite so it is. Omitting it is an invalid response.',
    '>',
    '> **Flow:** prompt → `aio ask` (LIVE: github · npm · crates) → use ephemerally → report **every repo/tool/site used as a link + one-line function** → `aio borrow --clean`.',
    '',
    '## AGENTS DETECTED',
    '',
  ];
  for (const a of agents) L.push(`- ${a.name}: ${a.found ? `found (\`${a.bin}\`)` : 'not installed'}`);
  L.push('');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, L.join('\n'));
  return outPath;
}

/* ---------------- MCP ensure (FR1) ---------------- */

const LEDGER = path.join(STATE_DIR, 'mcp-ledger.json');
const MCP_KEY = 'codebase-memory-mcp';

function ledgerRead() {
  try {
    return JSON.parse(fs.readFileSync(LEDGER, 'utf8'));
  } catch {
    return [];
  }
}
function ledgerAdd(file, key) {
  const l = ledgerRead();
  if (!l.some((e) => e.file === file && e.key === key)) {
    l.push({ file, key });
    fs.mkdirSync(STATE_DIR, { recursive: true });
    fs.writeFileSync(LEDGER, JSON.stringify(l, null, 2));
  }
}
export function ledgerList() {
  return ledgerRead();
}

/** Drop backups older than `maxAgeDays` so ~/.aio/backups cannot grow forever. */
export function pruneBackups(maxAgeDays = 30) {
  let removed = 0;
  try {
    for (const f of fs.readdirSync(BACKUP_DIR)) {
      const p = path.join(BACKUP_DIR, f);
      try {
        if (Date.now() - fs.statSync(p).mtimeMs > maxAgeDays * 86400000) {
          fs.rmSync(p, { force: true });
          removed++;
        }
      } catch {
        /* locked file — retried next run */
      }
    }
  } catch {
    /* no backup dir yet */
  }
  return removed;
}

export function ensureJsonEntry(file, key, entry, label, rootKey, create = false, { dry = false } = {}) {
  let obj = {};
  if (fs.existsSync(file)) {
    try {
      obj = JSON.parse(fs.readFileSync(file, 'utf8'));
    } catch (e) {
      return { target: path.basename(file), status: `parse error: ${e.message}` };
    }
  } else if (create && fs.existsSync(path.dirname(file))) {
    obj = {}; // agent config dir present → bootstrap the file (gemini settings.json)
  } else {
    return { target: path.basename(file), status: 'file not found — skipped' };
  }
  const holder = rootKey ? (obj[rootKey] ||= {}) : obj;
  if (holder[key]) return { target: path.basename(file), status: 'present' };
  if (dry) return { target: path.basename(file), status: 'would add (dry-run)' };
  backup(file, label);
  holder[key] = entry;
  const text = JSON.stringify(obj, null, 2) + '\n';
  JSON.parse(text); // verify before write
  fs.writeFileSync(file, text);
  ledgerAdd(file, key);
  return { target: path.basename(file), status: 'added' };
}

/** codex config.toml: append [mcp_servers.<key>] only when absent. */
export function ensureTomlEntry(file, key, entry, label, { dry = false } = {}) {
  if (!fs.existsSync(file)) return { target: path.basename(file), status: 'file not found — skipped' };
  const txt = fs.readFileSync(file, 'utf8');
  const header = `[mcp_servers.${key}]`;
  if (txt.includes(header) || txt.includes(`[mcp_servers."${key}"]`)) {
    return { target: path.basename(file), status: 'present' };
  }
  if (dry) return { target: path.basename(file), status: 'would add (dry-run)' };
  backup(file, label);
  const body = Object.entries(entry)
    .map(([k, v]) => `${k} = ${JSON.stringify(v)}`)
    .join('\n');
  fs.writeFileSync(file, txt.replace(/\s*$/, '') + `\n\n${header}\n${body}\n`);
  ledgerAdd(file, key);
  return { target: path.basename(file), status: 'added' };
}

/** opencode.jsonc is JSONC (comments must survive) → textual insert. */
function ensureOpencodeJsonc(key, entry, { dry = false } = {}) {
  const file = path.join(os.homedir(), '.config', 'opencode', 'opencode.jsonc');
  if (!fs.existsSync(file)) return { target: 'opencode.jsonc', status: 'file not found — skipped' };
  const txt = fs.readFileSync(file, 'utf8');
  // key must be an object key ("<key>":), not a random mention of the string
  if (new RegExp(`"${key}"\\s*:`).test(txt)) return { target: 'opencode.jsonc', status: 'present' };
  const markerMatch = txt.match(/"mcp"\s*:\s*\{/); // tolerate spacing/newline variants
  if (!markerMatch) return { target: 'opencode.jsonc', status: 'no "mcp" block — skipped' };
  if (dry) return { target: 'opencode.jsonc', status: 'would add (dry-run)' };
  backup(file, 'opencode-jsonc');
  const idx = markerMatch.index;
  const marker = markerMatch[0];
  const after = txt.slice(idx + marker.length);
  const empty = /^\s*\}/.test(after);
  const insert = `${marker}\n    ${JSON.stringify(key)}: ${JSON.stringify(entry)}${empty ? '' : ','}`;
  const next = txt.slice(0, idx) + insert + after;
  fs.writeFileSync(file, next);
  ledgerAdd(file, key);
  return { target: 'opencode.jsonc', status: 'added' };
}

/** Ensure codebase-memory-mcp exists in opencode / claude / kimi / jcode / codex / gemini configs. */
export function ensureMcp(binary, { dry = false } = {}) {
  const entry = { command: binary };
  const home = os.homedir();
  const results = [];
  results.push(ensureOpencodeJsonc(MCP_KEY, { type: 'local', command: binary }, { dry }));
  results.push(
    ensureJsonEntry(path.join(home, '.claude.json'), MCP_KEY, entry, 'claude-json', 'mcpServers', false, { dry })
  );
  results.push(
    ensureJsonEntry(path.join(home, '.kimi-code', 'mcp.json'), MCP_KEY, entry, 'kimi-mcp', 'mcpServers', false, { dry })
  );
  results.push(
    ensureJsonEntry(path.join(home, '.jcode', 'mcp.json'), MCP_KEY, entry, 'jcode-mcp', 'servers', false, { dry })
  );
  results.push(
    ensureJsonEntry(path.join(home, '.gemini', 'settings.json'), MCP_KEY, entry, 'gemini-settings', 'mcpServers', true, { dry })
  );
  results.push(ensureTomlEntry(path.join(home, '.codex', 'config.toml'), MCP_KEY, entry, 'codex-toml', { dry }));
  return results;
}

/** Reverse exactly what ensureMcp added (recorded in the ledger).
 *  Per-file try/catch: a malformed config is reported, never crashed on, and its
 *  ledger entry is KEPT so rollback can retry after the user fixes the file.
 *  A temporarily missing file is also KEPT (retry when it reappears); a file
 *  whose key is genuinely gone drops out of the ledger. Backups are taken only
 *  when a real modification is about to happen. */
export function removeMcpAdditions() {
  const out = [];
  const keep = [];
  for (const { file, key } of ledgerRead()) {
    if (!fs.existsSync(file)) {
      keep.push({ file, key });
      out.push({ target: path.basename(file), status: 'missing — ledger entry kept for retry' });
      continue;
    }
    const txt = fs.readFileSync(file, 'utf8');
    if (!txt.includes(key)) {
      out.push({ target: path.basename(file), status: 'already gone' });
      continue;
    }
    try {
      if (file.endsWith('.toml')) {
        const esc = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const re = new RegExp(`\\n?\\[mcp_servers\\."?${esc}"?\\][^\\[]*`, 'g');
        const next = txt.replace(re, '');
        if (next === txt) {
          out.push({ target: path.basename(file), status: 'already gone' });
          continue;
        }
        backup(file, 'rollback-mcp');
        fs.writeFileSync(file, next);
      } else if (file.endsWith('.jsonc')) {
        const re = new RegExp(`${JSON.stringify(key).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*:\\s*\\{[^{}]*\\},?\\s*`, 'g');
        const next = txt.replace(re, '');
        if (next === txt) {
          out.push({ target: path.basename(file), status: 'already gone' });
          continue;
        }
        backup(file, 'rollback-mcp');
        fs.writeFileSync(file, next);
      } else {
        const obj = JSON.parse(txt);
        let removed = false;
        for (const rk of ['mcpServers', 'servers']) {
          if (obj[rk] && typeof obj[rk] === 'object' && key in obj[rk]) {
            delete obj[rk][key];
            removed = true;
            break;
          }
        }
        if (key in obj) {
          delete obj[key];
          removed = true;
        }
        if (!removed) {
          out.push({ target: path.basename(file), status: 'already gone' });
          continue;
        }
        backup(file, 'rollback-mcp');
        fs.writeFileSync(file, JSON.stringify(obj, null, 2) + '\n');
      }
      out.push({ target: path.basename(file), status: 'removed' });
    } catch (e) {
      keep.push({ file, key });
      out.push({ target: path.basename(file), status: `parse error — skipped, ledger entry kept (${String(e.message).slice(0, 60)})` });
    }
  }
  fs.writeFileSync(LEDGER, JSON.stringify(keep, null, 2));
  return out;
}

/* ---------------- stale path repair ---------------- */

const STALE_FROM = 'AI tutorial';
const STALE_TO = 'all-in-one';

/** Repair registry pointers broken by the folder rename. Returns per-file results. dry = report only. */
export function fixPaths(dry = false) {
  const home = os.homedir();
  const targets = [
    path.join(home, 'AGENTS.md'),
    path.join(home, '.claude', 'CLAUDE.md'),
    path.join(home, '.config', 'opencode', 'AGENTS.md'),
    path.join(home, '.kimi-code', 'AGENTS.md'),
    path.join(home, '.jcode', 'AGENTS.md'),
    path.join(home, '.codex', 'AGENTS.md'),
    path.join(home, '.gemini', 'GEMINI.md'),
  ];
  const results = [];
  for (const file of targets) {
    if (!fs.existsSync(file)) continue;
    const txt = fs.readFileSync(file, 'utf8');
    if (!txt.includes(STALE_FROM)) continue;
    const count = txt.split(STALE_FROM).length - 1;
    if (dry) {
      results.push({ target: file, status: `would repair ${count} path reference(s) (dry-run)` });
      continue;
    }
    backup(file, 'pathfix');
    fs.writeFileSync(file, txt.split(STALE_FROM).join(STALE_TO));
    results.push({ target: file, status: `repaired ${count} path reference(s)` });
  }
  return results;
}
