// write.js — backups, block injection, context manifest, MCP ensure, path repair
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { BACKUP_DIR, STATE_DIR } from './paths.js';

export const BLOCK_START = '<!-- aio:auto-config:v1:start -->';
export const BLOCK_END = '<!-- aio:auto-config:v1:end -->';
const BLOCK_RE = /<!-- aio:auto-config:v1:start -->[\s\S]*?<!-- aio:auto-config:v1:end -->/;

export function backup(file, label) {
  if (!fs.existsSync(file)) return null;
  fs.mkdirSync(BACKUP_DIR, { recursive: true });
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const safe = String(label).replace(/[^a-z09_-]/gi, '_');
  const dest = path.join(BACKUP_DIR, `${safe}__${ts}__${path.basename(file)}`);
  fs.copyFileSync(file, dest);
  return dest;
}

/** Build the auto-use rule block (FR2 + FR6: usage disclosure format). */
export function buildBlock({ version, manifestPath, dataDir }) {
  const lines = [
    `### AIO AUTO-CONTEXT (generated by aio v${version} — do not edit; re-run \`aio\` to refresh)`,
    '',
    `- Context manifest (auto-generated): \`${manifestPath}\``,
  ];
  if (dataDir) {
    if (fs.existsSync(path.join(dataDir, 'TOOLS-INDEX.md'))) {
      lines.push(`- Tools registry: \`${path.join(dataDir, 'TOOLS-INDEX.md')}\``);
    }
    if (fs.existsSync(path.join(dataDir, 'ai-tools.db'))) {
      lines.push(`- Local tools DB (SQLite): \`${path.join(dataDir, 'ai-tools.db')}\``);
    }
  }
  lines.push(
    '',
    'Auto-use rules (plain-language prompts only — NO slash-commands required):',
    '1. USAGE DISCLOSURE (MANDATORY — applies on EVERY turn, no exceptions):',
    '   The moment you read, list, cite, compare, recommend, summarize, or otherwise use ANY entry from the manifest above — even one line, even indirectly — your reply MUST START with this exact line as the very FIRST line of your answer:',
    '   [aio] Using [<name>](<url>) (<type>) — <function>',
    '   where [<name>](<url>) is a MARKDOWN LINK to that entry\'s URL from the manifest (the link is required — option 2), <type> = repo | cli | service | skill, and <function> = the entry\'s one-line description.',
    '   Example first line: [aio] Using [Stirling-PDF](https://github.com/Stirling-Tools/Stirling-PDF) (repo) — HTML/CSS/JS to PDF converter',
    '   If an entry has no URL, keep the name plain: [aio] Using markitdown (cli) — …',
    '   SELF-CHECK BEFORE SENDING: "Did this answer draw on the manifest in any way?" If yes and line 1 is not the [aio] disclosure line → REWRITE the reply so the disclosure line comes first. A response that uses the manifest without the disclosure line is an INVALID response and must be corrected before you send it.',
    '   Never put the line after the answer, never paraphrase or shorten it, never skip it because the answer is short, and never assume the user already knows what you used. This is non-negotiable: no circumstance excuses omitting it.',
    '2. When a prompt involves a local repository, tool, service, or skill, read the manifest above and route yourself to the matching entry on your own — never ask the user to type `/command` for routing.',
    '3. Prefer manifest entries (already installed locally) over proposing new installs.',
    '4. If the user mentions a repo/tool that is not in the manifest, tell them to run `aio` again to rescan.',
    '5. Reply in the user’s language.'
  );
  return lines.join('\n');
}

/** Idempotent marker injection: first run appends, later runs replace in place. */
export function injectBlock(file, body, label) {
  const existed = fs.existsSync(file);
  const current = existed ? fs.readFileSync(file, 'utf8') : '';
  const had = BLOCK_RE.test(current);
  const block = `${BLOCK_START}\n${body}\n${BLOCK_END}`;
  const next = had
    ? current.replace(BLOCK_RE, block)
    : (current ? current.replace(/\s*$/, '\n\n') : '') + block + '\n';
  if (next === current) return { status: 'unchanged', file };
  if (existed) backup(file, label);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, next);
  return { status: had ? 'updated' : 'injected', file };
}

/** Surgically remove the block (rollback, FR7). Returns 'removed' | 'absent'. */
export function stripBlock(file) {
  if (!fs.existsSync(file)) return 'absent';
  const current = fs.readFileSync(file, 'utf8');
  if (!BLOCK_RE.test(current)) return 'absent';
  backup(file, 'rollback');
  const next = current.replace(BLOCK_RE, '').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n';
  fs.writeFileSync(file, next);
  return 'removed';
}

/** Generate the context manifest (FR3): REPOS + TOOLS + SKILLS. */
export function genContext({ version, dataDir, reposDir, repos, tools, skills, agents }, outPath) {
  const now = new Date().toISOString();
  const L = [
    `<!-- AUTO-GENERATED by aio v${version} on ${now} — do not edit; run \`aio\` to refresh -->`,
    '',
    '# AIO Context Manifest',
    '',
    `> Repos dir: \`${reposDir || '(not configured — pass --repos <dir> or set AIO_REPOS_DIR)'}\``,
    dataDir ? `> Data dir: \`${dataDir}\`` : '> Data dir: (none — tools registry / DB not found)',
    '>',
    '> **MANDATORY disclosure** — the moment your answer uses ANY entry from this file (read, listed, cited, or recommended), START your reply with this exact line:',
    '>',
    '> `[aio] Using [<name>](<url>) (<type>) — <function>`',
    '>',
    '> where `[<name>](<url>)` is a Markdown link to that entry\'s URL from this file, `<type>` = repo | cli | service | skill, `<function>` = its one-line description. Example first line: `[aio] Using [Stirling-PDF](https://github.com/Stirling-Tools/Stirling-PDF) (repo) — HTML/CSS/JS to PDF converter`. Self-check before sending: if this answer draws on this manifest and line 1 is not the `[aio]` line → rewrite so it is. Omitting it is an invalid response.',
    '',
    `## REPOS (${repos.length})`,
    '',
    repos.length
      ? ['| # | Repository | URL | Local path |', '|---|---|---|---|']
          .concat(repos.map((r, i) => `| ${i + 1} | ${r.name} | ${r.url || '— (local only)'} | \`${r.path}\` |`))
          .join('\n')
      : '_No cloned repositories found._',
    '',
    `## TOOLS (${tools.length})`,
    '',
    tools.length
      ? ['| Tool | What it does | Access / command | Version | Link |', '|---|---|---|---|---|']
          .concat(
            tools.map(
              (t) =>
                `| ${t.name} | ${t.description || '—'} | \`${(t.access || '').replace(/\|/g, '\\|')}\` | ${t.version || '—'} | ${t.url || '—'} |`
            )
          )
          .join('\n')
      : '_No tools catalog found (ai-tools.db / TOOLS-INDEX.md)._',
    '',
    `## SKILLS (${skills.reduce((n, s) => n + s.count, 0)})`,
    '',
  ];
  for (const loc of skills) {
    L.push(`- \`${loc.location}\` — ${loc.count} skills`);
    if (loc.count) L.push(`  - ${loc.names.join(', ')}`);
  }
  L.push('', '## AGENTS DETECTED', '');
  for (const a of agents) L.push(`- ${a.name}: ${a.found ? `found (\`${a.bin}\`)` : 'not installed'}`);
  L.push('');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  fs.writeFileSync(outPath, L.join('\n'));
  return outPath;
}

/* ---------------- MCP ensure (FR1) ---------------- */

const LEDGER = path.join(STATE_DIR, 'mcp-ledger.json');
const MCP_KEY = 'codebase-memory-mcp';

function ledgerRead() {
  try {
    return JSON.parse(fs.readFileSync(LEDGER, 'utf8'));
  } catch {
    return [];
  }
}
function ledgerAdd(file, key) {
  const l = ledgerRead();
  if (!l.some((e) => e.file === file && e.key === key)) {
    l.push({ file, key });
    fs.mkdirSync(STATE_DIR, { recursive: true });
    fs.writeFileSync(LEDGER, JSON.stringify(l, null, 2));
  }
}
export function ledgerList() {
  return ledgerRead();
}

export function ensureJsonEntry(file, key, entry, label, rootKey, create = false) {
  let obj = {};
  if (fs.existsSync(file)) {
    try {
      obj = JSON.parse(fs.readFileSync(file, 'utf8'));
    } catch (e) {
      return { target: path.basename(file), status: `parse error: ${e.message}` };
    }
  } else if (create && fs.existsSync(path.dirname(file))) {
    obj = {}; // agent config dir present → bootstrap the file (gemini settings.json)
  } else {
    return { target: path.basename(file), status: 'file not found — skipped' };
  }
  const holder = rootKey ? (obj[rootKey] ||= {}) : obj;
  if (holder[key]) return { target: path.basename(file), status: 'present' };
  backup(file, label);
  holder[key] = entry;
  const text = JSON.stringify(obj, null, 2) + '\n';
  JSON.parse(text); // verify before write
  fs.writeFileSync(file, text);
  ledgerAdd(file, key);
  return { target: path.basename(file), status: 'added' };
}

/** codex config.toml: append [mcp_servers.<key>] only when absent. */
export function ensureTomlEntry(file, key, entry, label) {
  if (!fs.existsSync(file)) return { target: path.basename(file), status: 'file not found — skipped' };
  const txt = fs.readFileSync(file, 'utf8');
  const header = `[mcp_servers.${key}]`;
  if (txt.includes(header) || txt.includes(`[mcp_servers."${key}"]`)) {
    return { target: path.basename(file), status: 'present' };
  }
  backup(file, label);
  const body = Object.entries(entry)
    .map(([k, v]) => `${k} = ${JSON.stringify(v)}`)
    .join('\n');
  fs.writeFileSync(file, txt.replace(/\s*$/, '') + `\n\n${header}\n${body}\n`);
  ledgerAdd(file, key);
  return { target: path.basename(file), status: 'added' };
}

/** opencode.jsonc is JSONC (comments must survive) → textual insert. */
function ensureOpencodeJsonc(key, entry) {
  const file = path.join(os.homedir(), '.config', 'opencode', 'opencode.jsonc');
  if (!fs.existsSync(file)) return { target: 'opencode.jsonc', status: 'file not found — skipped' };
  const txt = fs.readFileSync(file, 'utf8');
  if (txt.includes(`"${key}"`)) return { target: 'opencode.jsonc', status: 'present' };
  const marker = '"mcp": {';
  const idx = txt.indexOf(marker);
  if (idx === -1) return { target: 'opencode.jsonc', status: 'no "mcp" block — skipped' };
  backup(file, 'opencode-jsonc');
  const after = txt.slice(idx + marker.length);
  const empty = /^\s*\}/.test(after);
  const insert = `${marker}\n    ${JSON.stringify(key)}: ${JSON.stringify(entry)}${empty ? '' : ','}`;
  const next = txt.slice(0, idx) + insert + after;
  fs.writeFileSync(file, next);
  ledgerAdd(file, key);
  return { target: 'opencode.jsonc', status: 'added' };
}

/** Ensure codebase-memory-mcp exists in opencode / claude / kimi / jcode / codex / gemini configs. */
export function ensureMcp(binary) {
  const entry = { command: binary };
  const home = os.homedir();
  const results = [];
  results.push(ensureOpencodeJsonc(MCP_KEY, { type: 'local', command: binary }));
  results.push(
    ensureJsonEntry(path.join(home, '.claude.json'), MCP_KEY, entry, 'claude-json', 'mcpServers')
  );
  results.push(
    ensureJsonEntry(path.join(home, '.kimi-code', 'mcp.json'), MCP_KEY, entry, 'kimi-mcp', 'mcpServers')
  );
  results.push(
    ensureJsonEntry(path.join(home, '.jcode', 'mcp.json'), MCP_KEY, entry, 'jcode-mcp', 'servers')
  );
  results.push(
    ensureJsonEntry(path.join(home, '.gemini', 'settings.json'), MCP_KEY, entry, 'gemini-settings', 'mcpServers', true)
  );
  results.push(ensureTomlEntry(path.join(home, '.codex', 'config.toml'), MCP_KEY, entry, 'codex-toml'));
  return results;
}

/** Reverse exactly what ensureMcp added (recorded in the ledger). */
export function removeMcpAdditions() {
  const out = [];
  for (const { file, key } of ledgerRead()) {
    if (!fs.existsSync(file)) {
      out.push({ target: path.basename(file), status: 'missing' });
      continue;
    }
    const txt = fs.readFileSync(file, 'utf8');
    if (!txt.includes(key)) {
      out.push({ target: path.basename(file), status: 'already gone' });
      continue;
    }
    backup(file, 'rollback-mcp');
    if (file.endsWith('.toml')) {
      const esc = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
      const re = new RegExp(`\\n?\\[mcp_servers\\."?${esc}"?\\][^\\[]*`, 'g');
      fs.writeFileSync(file, txt.replace(re, ''));
    } else if (file.endsWith('.jsonc')) {
      const re = new RegExp(`${JSON.stringify(key).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*:\\s*\\{[^{}]*\\},?\\s*`, 'g');
      fs.writeFileSync(file, txt.replace(re, ''));
    } else {
      const obj = JSON.parse(txt);
      for (const rk of ['mcpServers', 'servers']) {
        if (obj[rk] && typeof obj[rk] === 'object' && key in obj[rk]) {
          delete obj[rk][key];
          break;
        }
      }
      if (key in obj) delete obj[key];
      fs.writeFileSync(file, JSON.stringify(obj, null, 2) + '\n');
    }
    out.push({ target: path.basename(file), status: 'removed' });
  }
  fs.writeFileSync(LEDGER, '[]');
  return out;
}

/* ---------------- stale path repair ---------------- */

const STALE_FROM = 'AI tutorial';
const STALE_TO = 'all-in-one-repo';

/** Repair registry pointers broken by the folder rename. Returns per-file results. */
export function fixPaths() {
  const home = os.homedir();
  const targets = [
    path.join(home, 'AGENTS.md'),
    path.join(home, '.claude', 'CLAUDE.md'),
    path.join(home, '.config', 'opencode', 'AGENTS.md'),
    path.join(home, '.kimi-code', 'AGENTS.md'),
    path.join(home, '.jcode', 'AGENTS.md'),
    path.join(home, '.codex', 'AGENTS.md'),
    path.join(home, '.gemini', 'GEMINI.md'),
  ];
  const results = [];
  for (const file of targets) {
    if (!fs.existsSync(file)) continue;
    const txt = fs.readFileSync(file, 'utf8');
    if (!txt.includes(STALE_FROM)) continue;
    const count = txt.split(STALE_FROM).length - 1;
    backup(file, 'pathfix');
    fs.writeFileSync(file, txt.split(STALE_FROM).join(STALE_TO));
    results.push({ target: file, status: `repaired ${count} path reference(s)` });
  }
  return results;
}
