// write.js — backups, block injection, context manifest, MCP ensure
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { BACKUP_DIR, STATE_DIR, writeAtomic, preserveCorrupt } from './paths.js';

export const BLOCK_START = '<!-- aio:auto-config:v1:start -->';
export const BLOCK_END = '<!-- aio:auto-config:v1:end -->';
// Detection/match (first block only, no lastIndex state) vs replace-all: a file
// that somehow carries TWO blocks must still collapse to exactly one (6a).
const BLOCK_RE = /<!-- aio:auto-config:v1:start -->[\s\S]*?<!-- aio:auto-config:v1:end -->/;
const BLOCK_RE_G = /<!-- aio:auto-config:v1:start -->[\s\S]*?<!-- aio:auto-config:v1:end -->/g;

export function backup(file, label) {
  if (!fs.existsSync(file)) return null;
  fs.mkdirSync(BACKUP_DIR, { recursive: true });
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const safe = String(label).replace(/[^a-z0-9_-]/gi, '_');
  const base = `${safe}__${ts}__${path.basename(file)}`;
  // two backups in the same millisecond must not overwrite each other (CI race)
  let dest = path.join(BACKUP_DIR, base);
  for (let i = 1; fs.existsSync(dest); i++) {
    dest = path.join(BACKUP_DIR, `${safe}__${ts}_${i}__${path.basename(file)}`);
  }
  fs.copyFileSync(file, dest);
  return dest;
}

/** Build the auto-use rule block (FR2 + FR6: usage disclosure format).
 *  manifestPath is optional: project-only runs (`aio init` on a machine that
 *  never ran global `aio`) omit the pointer line instead of shipping a
 *  dangling path (W4). */
export function buildBlock({ version, manifestPath }) {
  const lines = [
    `### AIO AUTO-CONTEXT (generated by aio v${version} — do not edit; re-run \`aio\` to refresh)`,
  ];
  if (manifestPath) lines.push('', `- Context manifest (auto-generated): \`${manifestPath}\``);
  lines.push(
    '',
    'Auto-use rules (plain-language prompts only — NO slash-commands required):',
    '0. FIRST LINE RULE (non-negotiable, applies BEFORE anything else): if ANY part of this reply used something aio surfaced (`aio ask`/`aio borrow`/this manifest — read, cited, listed, recommended), line 1 MUST be exactly:',
    '   [aio] Using [<name>](<url>) (<type>) — <function>',
    '   Nothing else may sit on line 1 while it applies. Missing it, moving it, or shortening it invalidates the reply — rewrite before sending. (Read rule 1 for the full contract + example.)',
    '1. USAGE DISCLOSURE — required the moment your reply uses ANY entry surfaced through aio (via `aio ask`/`aio borrow`/this manifest: read, cited, listed, or recommended). Pure code Q&A with zero aio-surfaced entries does NOT trigger it. When triggered, your FIRST line must be exactly the rule 0 format — where [<name>](<url>) = markdown link to the entry\'s URL (plain name if none), <type> = repo | cli | service | skill | site, <function> = its one-line description. Example: [aio] Using [Stirling-PDF](https://github.com/Stirling-Tools/Stirling-PDF) (repo) — HTML/CSS/JS to PDF converter.',
    '   Self-check before sending: did this answer use any aio-surfaced entry? If yes and line 1 is not the disclosure → rewrite so it is. Never move/shorten/skip it, even for short answers — without it the response is invalid.',
    '2. PROMPT → LIVE SEARCH → USE → REPORT (every agent, no exceptions):',
    '   a. Prompt needs a repo/tool/skill → run `aio ask "<prompt words>"` FIRST — it searches LIVE (GitHub 630M+ repos + public skills, npm, crates), adaptive to your intent, ZERO storage: results are never saved anywhere.',
    '   b. Websites/URLs → use your own built-in web search (automatic, no key needed). aio ask covers code sources; not-in-ask is never a dead end.',
    '   c. Need the files locally → `aio borrow --get <owner/repo>` (temp clone, 24h TTL), `npx`/`uvx` — never permanent installs or bulk downloads.',
    '   d. Final report lists WHAT CHANGED + EVERY repo/tool/site used as a markdown link with its one-line function, e.g. `- [[d3](https://github.com/d3/d3)] — chart library, rendered the bar chart`.',
    '   e. When done, run `aio borrow --clean`.',
    '3. Prompt involves a local repo/tool/service/skill → route yourself; never ask the user to type `/command`.',
    '4. Prefer already-installed/local things over proposing new installs.',
    '5. The catalog is unlimited because it is live — when `aio ask` returns nothing, re-query once with different keywords; if it still returns nothing, say so plainly. Never claim a thing is unavailable without searching, and never invent availability.',
    '6. Reply in the user’s language.'
  );
  return lines.join('\n');
}

/* ---- drift detection (C-02): hash of the block aio last wrote, per file.
   A current block whose hash differs → edited by hand; setup/status warn
   instead of silently clobbering. Stored in ~/.aio/block-hashes.json. ---- */
const HASHES = path.join(STATE_DIR, 'block-hashes.json');

const hashOf = (s) => crypto.createHash('sha256').update(String(s)).digest('hex').slice(0, 16);

// One key builder for every read/write of block-hashes.json: resolve + lowercase
// on win32 (case-insensitive fs — C:\Users vs c:\users is the SAME file, and a
// key mismatch would show up as phantom "hand-edited" drift) (6f).
const hashKey = (file) => {
  const k = path.resolve(file);
  return process.platform === 'win32' ? k.toLowerCase() : k;
};

function hashesRead() {
  let raw;
  try {
    raw = fs.readFileSync(HASHES, 'utf8');
  } catch {
    return {}; // nothing recorded yet — same as an empty state
  }
  try {
    const o = JSON.parse(raw);
    return o && typeof o === 'object' ? o : {};
  } catch {
    // CORRUPT → null, not {}: rebuilding the drift state from {} would let the
    // next write silently claim "no drift" for every block ever written. The bad
    // bytes are preserved aside; callers must refuse to write until it's fixed.
    preserveCorrupt(HASHES);
    return null;
  }
}

function rememberBlock(file, body) {
  const h = hashesRead();
  if (!h) return; // corrupt preserved aside — never rebuild drift hashes from scratch
  const k = hashKey(file);
  const digest = hashOf(body);
  if (h[k] === digest) return; // already recorded — re-writing the same bytes is a no-op (7b)
  h[k] = digest;
  fs.mkdirSync(STATE_DIR, { recursive: true });
  writeAtomic(HASHES, JSON.stringify(h, null, 2));
}

/** Current marker-delimited block in `file`, or null. */
export function currentBlock(file) {
  if (!fs.existsSync(file)) return null;
  const m = fs.readFileSync(file, 'utf8').match(BLOCK_RE);
  return m ? m[0] : null;
}

/** True when the block on disk no longer matches what aio last wrote. */
export function blockEdited(file) {
  const cur = currentBlock(file);
  if (!cur) return false;
  const stored = hashesRead()?.[hashKey(file)]; // corrupt state → no drift claim (preserved aside)
  return !!stored && hashOf(cur) !== stored;
}

/** Idempotent marker injection: first run appends, later runs replace in place.
 *  opts.dry → compute the planned status only; no backup, no write (FR12 dry-run).
 *  Hand-edited blocks are reported as such (C-02) — the replacement always lands
 *  in ~/.aio/backups/ first, so nothing the user wrote is lost. */
export function injectBlock(file, body, label, { dry = false } = {}) {
  const existed = fs.existsSync(file);
  const current = existed ? fs.readFileSync(file, 'utf8') : '';
  const had = BLOCK_RE.test(current);
  const edited = had && blockEdited(file);
  const block = `${BLOCK_START}\n${body}\n${BLOCK_END}`;
  let next;
  if (had) {
    // collapse any duplicated blocks to exactly ONE at the first block's position
    // (content around them survives) — a stray second block can't stay behind (6a)
    const idx = current.search(BLOCK_RE);
    next = current.slice(0, idx) + block + current.slice(idx).replace(BLOCK_RE_G, '');
  } else {
    next = (current ? current.replace(/\s*$/, '\n\n') : '') + block + '\n';
  }
  if (next === current) {
    // block already exactly what aio writes → record/refresh its drift hash so
    // future hand-edits are detectable (pre-1.5 files never got a hash entry).
    // Plan phase stays read-only: never write state from a dry run (B1).
    // rememberBlock itself skips the write when the digest already matches (7b).
    if (!dry && had) rememberBlock(file, block);
    return { status: 'unchanged', file };
  }
  if (dry) {
    const verb = had ? (edited ? 'would update (hand-edit detected)' : 'would update') : 'would inject';
    return { status: `${verb} (dry-run)`, file };
  }
  if (existed) backup(file, label);
  fs.mkdirSync(path.dirname(file), { recursive: true });
  writeAtomic(file, next);
  rememberBlock(file, block);
  const upd = had ? (edited ? 'updated (hand-edit replaced — kept in backups/)' : 'updated') : 'injected';
  return { status: upd, file };
}

/** Drop a file's drift-hash entry (block removed or never present). */
function pruneHash(file) {
  const h = hashesRead();
  if (!h) return; // corrupt preserved aside — never rewrite the state from scratch
  const k = hashKey(file);
  if (k in h) {
    delete h[k];
    fs.mkdirSync(STATE_DIR, { recursive: true });
    writeAtomic(HASHES, JSON.stringify(h, null, 2));
  }
}

/** Surgically remove the block (rollback, FR7). Returns 'removed' | 'absent'. */
export function stripBlock(file) {
  if (!fs.existsSync(file)) {
    pruneHash(file); // file gone entirely — don't leave a stale drift key (N5)
    return 'absent';
  }
  const current = fs.readFileSync(file, 'utf8');
  if (!BLOCK_RE.test(current)) {
    pruneHash(file); // hand-deleted block — stale key would outlive it (N5)
    return 'absent';
  }
  backup(file, 'rollback');
  const next = current.replace(BLOCK_RE_G, '').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n'; // all copies (6a)
  writeAtomic(file, next);
  pruneHash(file);
  return 'removed';
}

/** Generate the slim context manifest (FR3 + FR11): pointer + detected agents.
 *  The auto-use rules + disclosure live ONLY in the injected block (single source
 *  of truth — M-04): no duplicated rules, no token double-cost per session. */
export function genContext({ version, agents }, outPath) {
  const now = new Date().toISOString();
  const L = [
    `<!-- AUTO-GENERATED by aio v${version} on ${now} — do not edit; run \`aio\` to refresh -->`,
    '',
    '# AIO Context Manifest',
    '',
    '> **Live architecture — zero search storage.** No catalog database exists: `aio ask` searches GitHub (630M+ repos + public skills), npm (3M+ packages) and crates (340K+) in real time; websites via your own web search. Results are printed and discarded — **no search history is kept**. (aio does write its own files: this manifest, one block per agent, timestamped backups under `~/.aio/backups/`, a rate-limit clock — timestamps only, never queries — and a skills ledger only if you use `aio skill add`.)',
    '>',
    '> **Rules & mandatory disclosure** live in the `AIO AUTO-CONTEXT` block inside this agent\'s instruction file — single source of truth; this manifest only carries status (which rules and which agents).',
    '>',
    '> **Flow:** prompt → `aio ask` (LIVE: github · npm · crates) → use ephemerally → report every repo/tool/site used as a link + one-line function → `aio borrow --clean`.',
    '',
    '## AGENTS DETECTED',
    '',
  ];
  for (const a of agents) L.push(`- ${a.name}: ${a.found ? `found (\`${a.bin}\`)` : 'not installed'}`);
  L.push('');
  fs.mkdirSync(path.dirname(outPath), { recursive: true });
  writeAtomic(outPath, L.join('\n'));
  return outPath;
}

/* ---------------- MCP ensure (FR1) ---------------- */

const LEDGER = path.join(STATE_DIR, 'mcp-ledger.json');
const MCP_KEY = 'codebase-memory-mcp';

function ledgerRead() {
  let raw;
  try {
    raw = fs.readFileSync(LEDGER, 'utf8');
  } catch {
    return []; // no ledger yet = aio recorded nothing (missing ≠ corrupt)
  }
  try {
    const o = JSON.parse(raw);
    if (Array.isArray(o)) return o;
  } catch {
    /* fall through — invalid JSON is corrupt too */
  }
  // CORRUPT (truncated/invalid/shapeless): preserving it aside is not enough —
  // a [] read-back would make the remove* paths PERMANENTLY wipe the record on
  // the next write. Hand callers this sentinel so they refuse to write instead.
  return { corrupt: true, path: preserveCorrupt(LEDGER) };
}
function ledgerAdd(file, key) {
  const r = ledgerRead();
  const l = Array.isArray(r) ? r : []; // corrupt preserved aside → start a fresh record
  if (!l.some((e) => e.file === file && e.key === key)) {
    l.push({ file, key });
    fs.mkdirSync(STATE_DIR, { recursive: true });
    writeAtomic(LEDGER, JSON.stringify(l, null, 2));
  }
}
export function ledgerList() {
  const r = ledgerRead();
  return Array.isArray(r) ? r : [];
}
export function ledgerFile() {
  return LEDGER;
}

/** Drop backups older than `maxAgeDays` so ~/.aio/backups cannot grow forever. */
export function pruneBackups(maxAgeDays = 30) {
  let removed = 0;
  try {
    for (const f of fs.readdirSync(BACKUP_DIR)) {
      const p = path.join(BACKUP_DIR, f);
      try {
        if (Date.now() - fs.statSync(p).mtimeMs > maxAgeDays * 86400000) {
          fs.rmSync(p, { force: true });
          removed++;
        }
      } catch {
        /* locked file — retried next run */
      }
    }
  } catch {
    /* no backup dir yet */
  }
  return removed;
}

export function ensureJsonEntry(file, key, entry, label, rootKey, create = false, { dry = false } = {}) {
  let obj = {};
  if (fs.existsSync(file)) {
    try {
      obj = JSON.parse(fs.readFileSync(file, 'utf8'));
    } catch (e) {
      return { target: path.basename(file), status: `parse error: ${e.message}` };
    }
  } else if (create && fs.existsSync(path.dirname(file))) {
    obj = {}; // agent config dir present → bootstrap the file (gemini settings.json)
  } else {
    return { target: path.basename(file), status: 'file not found — skipped' };
  }
  if (rootKey && (obj[rootKey] === null || typeof obj[rootKey] !== 'object' || Array.isArray(obj[rootKey]))) {
    obj[rootKey] = {}; // parseable-but-wrong-shape config (e.g. "mcpServers": "string") — rebuild, never TypeError
  }
  const holder = rootKey ? obj[rootKey] : obj;
  if (holder[key]) {
    // exact-shape match = aio's own entry → re-record it (self-healing ledger, S-01)
    if (!dry && JSON.stringify(holder[key]) === JSON.stringify(entry)) ledgerAdd(file, key);
    return { target: path.basename(file), status: 'present' };
  }
  if (dry) return { target: path.basename(file), status: 'would add (dry-run)' };
  backup(file, label);
  holder[key] = entry;
  writeAtomic(file, JSON.stringify(obj, null, 2) + '\n');
  ledgerAdd(file, key);
  return { target: path.basename(file), status: 'added' };
}

/** codex config.toml: append [mcp_servers.<key>] only when absent. */
export function ensureTomlEntry(file, key, entry, label, { dry = false } = {}) {
  if (!fs.existsSync(file)) return { target: path.basename(file), status: 'file not found — skipped' };
  const txt = fs.readFileSync(file, 'utf8');
  const header = `[mcp_servers.${key}]`;
  if (txt.includes(header) || txt.includes(`[mcp_servers."${key}"]`)) {
    // same command line = aio's own table → re-record it (self-healing ledger, S-01)
    if (!dry && typeof entry.command === 'string' && txt.includes(`command = ${JSON.stringify(entry.command)}`)) {
      ledgerAdd(file, key);
    }
    return { target: path.basename(file), status: 'present' };
  }
  if (dry) return { target: path.basename(file), status: 'would add (dry-run)' };
  backup(file, label);
  const body = Object.entries(entry)
    .map(([k, v]) => `${k} = ${JSON.stringify(v)}`)
    .join('\n');
  writeAtomic(file, txt.replace(/\s*$/, '') + `\n\n${header}\n# added by aio — remove via \`aio rollback\`\n${body}\n`);
  ledgerAdd(file, key);
  return { target: path.basename(file), status: 'added' };
}

/** opencode.jsonc is JSONC (comments must survive) → textual insert. */
function ensureOpencodeJsonc(key, entry, { dry = false } = {}) {
  const file = path.join(os.homedir(), '.config', 'opencode', 'opencode.jsonc');
  if (!fs.existsSync(file)) return { target: 'opencode.jsonc', status: 'file not found — skipped' };
  const txt = fs.readFileSync(file, 'utf8');
  // key must be an object key ("<key>":), not a random mention of the string.
  // Escape it — MCP keys aren't regex-safe by contract (same escaping as the
  // removal patterns below) (6g).
  const escKey = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  if (new RegExp(`"${escKey}"\\s*:`).test(txt)) {
    // same command = aio's own entry → re-record it (self-healing ledger, S-01)
    if (!dry && typeof entry.command === 'string' && txt.includes(JSON.stringify(entry.command))) ledgerAdd(file, key);
    return { target: 'opencode.jsonc', status: 'present' };
  }
  const markerMatch = txt.match(/"mcp"\s*:\s*\{/); // tolerate spacing/newline variants
  if (!markerMatch) return { target: 'opencode.jsonc', status: 'no "mcp" block — skipped' };
  if (dry) return { target: 'opencode.jsonc', status: 'would add (dry-run)' };
  backup(file, 'opencode-jsonc');
  const idx = markerMatch.index;
  const marker = markerMatch[0];
  const after = txt.slice(idx + marker.length);
  const empty = /^\s*\}/.test(after);
  // comment lives INSIDE the entry braces so a rollback removes it with the entry (S-01)
  const inner = Object.entries(entry)
    .map(([k, v]) => `${JSON.stringify(k)}: ${JSON.stringify(v)}`)
    .join(', ');
  const insert = `${marker}\n    ${JSON.stringify(key)}: { /* added by aio — remove via \`aio rollback\` */ ${inner} }${empty ? '' : ','}`;
  const next = txt.slice(0, idx) + insert + after;
  writeAtomic(file, next);
  ledgerAdd(file, key);
  return { target: 'opencode.jsonc', status: 'added' };
}

/** Ensure codebase-memory-mcp exists in opencode / claude / kimi / jcode / codex / gemini configs. */
export function ensureMcp(binary, { dry = false } = {}) {
  const entry = { command: binary };
  const home = os.homedir();
  const results = [];
  results.push(ensureOpencodeJsonc(MCP_KEY, { type: 'local', command: binary }, { dry }));
  results.push(
    ensureJsonEntry(path.join(home, '.claude.json'), MCP_KEY, entry, 'claude-json', 'mcpServers', false, { dry })
  );
  results.push(
    ensureJsonEntry(path.join(home, '.kimi-code', 'mcp.json'), MCP_KEY, entry, 'kimi-mcp', 'mcpServers', false, { dry })
  );
  results.push(
    ensureJsonEntry(path.join(home, '.jcode', 'mcp.json'), MCP_KEY, entry, 'jcode-mcp', 'servers', false, { dry })
  );
  results.push(
    ensureJsonEntry(path.join(home, '.gemini', 'settings.json'), MCP_KEY, entry, 'gemini-settings', 'mcpServers', true, { dry })
  );
  results.push(ensureTomlEntry(path.join(home, '.codex', 'config.toml'), MCP_KEY, entry, 'codex-toml', { dry }));
  return results;
}

/** Reverse exactly what ensureMcp added (recorded in the ledger).
 *  Per-file try/catch: a malformed config is reported, never crashed on, and its
 *  ledger entry is KEPT so rollback can retry after the user fixes the file.
 *  A temporarily missing file is also KEPT (retry when it reappears); a file
 *  whose key is genuinely gone drops out of the ledger. Backups are taken only
 *  when a real modification is about to happen. */
export function removeMcpAdditions() {
  const out = [];
  const keep = [];
  const ledger = ledgerRead();
  if (!Array.isArray(ledger)) {
    // corrupt ledger (preserved aside): writing keep=[] back would replace the
    // only recoverable copy with an empty record — refuse, loudly, via an out-row.
    return [{ target: 'mcp ledger', status: `ledger unreadable — preserved as ${ledger.path}, refusing to write` }];
  }
  for (const { file, key } of ledger) {
    if (!fs.existsSync(file)) {
      keep.push({ file, key });
      out.push({ target: path.basename(file), status: 'missing — ledger entry kept for retry' });
      continue;
    }
    const txt = fs.readFileSync(file, 'utf8');
    if (!txt.includes(key)) {
      out.push({ target: path.basename(file), status: 'already gone' });
      continue;
    }
    try {
      if (file.endsWith('.toml')) {
        const esc = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
        const re = new RegExp(`\\n?\\[mcp_servers\\."?${esc}"?\\][^\\[]*`, 'g');
        const next = txt.replace(re, '');
        // no match, or partial removal (a nested `[` inside aio's table stopped the
        // pattern) → honest status + ledger entry KEPT for retry; never write residue
        if (next === txt || next.includes(key)) {
          keep.push({ file, key });
          out.push({ target: path.basename(file), status: 'unsupported layout — manual removal needed, ledger entry kept' });
          continue;
        }
        backup(file, 'rollback-mcp');
        writeAtomic(file, next);
      } else if (file.endsWith('.jsonc')) {
        const re = new RegExp(`${JSON.stringify(key).replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s*:\\s*\\{[^{}]*\\},?\\s*`, 'g');
        const next = txt.replace(re, '');
        // nested-object entry the flat pattern can't match → same honest contract
        if (next === txt || next.includes(key)) {
          keep.push({ file, key });
          out.push({ target: path.basename(file), status: 'unsupported layout — manual removal needed, ledger entry kept' });
          continue;
        }
        backup(file, 'rollback-mcp');
        writeAtomic(file, next);
      } else {
        const obj = JSON.parse(txt);
        let removed = false;
        for (const rk of ['mcpServers', 'servers']) {
          if (obj[rk] && typeof obj[rk] === 'object' && key in obj[rk]) {
            delete obj[rk][key];
            removed = true;
            break;
          }
        }
        if (key in obj) {
          delete obj[key];
          removed = true;
        }
        if (!removed) {
          keep.push({ file, key });
          out.push({ target: path.basename(file), status: 'unsupported layout — manual removal needed, ledger entry kept' });
          continue;
        }
        backup(file, 'rollback-mcp');
        writeAtomic(file, JSON.stringify(obj, null, 2) + '\n');
      }
      out.push({ target: path.basename(file), status: 'removed' });
    } catch (e) {
      keep.push({ file, key });
      out.push({ target: path.basename(file), status: `parse error — skipped, ledger entry kept (${String(e.message).slice(0, 60)})` });
    }
  }
  fs.mkdirSync(STATE_DIR, { recursive: true }); // fresh machine: `aio rollback` before any state exists (F2)
  writeAtomic(LEDGER, JSON.stringify(keep, null, 2));
  return out;
}
